-- ============================================================
-- conAI — 300 productos reales (50 por categoría)
-- IMPORTANTE: borra todos los productos existentes
-- Ejecutar en Supabase > SQL Editor
-- ============================================================

TRUNCATE products CASCADE;

INSERT INTO products (name, description, price, category, icon, tag, stock, rating, review_count) VALUES

-- ============================================================
-- SALUD (50)
-- ============================================================
('Withings ScanWatch 2',      'Smartwatch médico con ECG, SpO2 y detección de apnea del sueño.',         349.99, 'salud', '❤️',   'bestseller', 15, 4.80, 312),
('Oura Ring Gen 3',           'Anillo con seguimiento de sueño, frecuencia cardíaca y temperatura.',      299.99, 'salud', '😴',   'bestseller', 20, 4.70, 524),
('Withings Body Scan',        'Báscula con análisis de composición corporal y salud cardiovascular.',     399.99, 'salud', '🧬',   NULL,         10, 4.50, 188),
('Muse S Headband',           'Diadema de meditación con biofeedback cerebral en tiempo real.',           399.99, 'salud', '🧘',   NULL,          8, 4.40, 143),
('Dexcom G7',                 'Sensor de glucosa continuo sin calibración con alertas inteligentes.',      89.99, 'salud', '💊',   'nuevo',      50, 4.60, 287),
('Wellue O2Ring',             'Monitor nocturno de oxígeno y frecuencia cardíaca con vibración.',         169.99, 'salud', '💙',   NULL,         18, 4.50, 201),
('Polar Vantage V3',          'Reloj de rendimiento deportivo con análisis de recuperación por IA.',      599.99, 'salud', '🏃',   'bestseller', 12, 4.80, 445),
('Apollo Neuro',              'Wearable de vibración táctil para reducir estrés y mejorar el foco.',     349.99, 'salud', '🧠',   'descuento',  14, 4.30, 167),
('Fitbit Charge 6',           'Pulsera de salud con ECG, SpO2 y análisis de estrés integrado.',          159.99, 'salud', '💚',   'bestseller', 30, 4.60, 892),
('Garmin Vívosmart 5',        'Rastreador delgado con monitoreo de energía corporal y sueño.',            149.99, 'salud', '🌿',   NULL,         25, 4.40, 367),
('Withings BPM Connect',      'Tensiómetro Wi-Fi con análisis automático y app de salud familiar.',      129.99, 'salud', '🩺',   NULL,         20, 4.50, 298),
('Kardia Mobile 6L',          'ECG de 6 derivaciones clínicas en el smartphone en 30 segundos.',         149.99, 'salud', '🫀',   'nuevo',      22, 4.70, 412),
('Omron Evolv',               'Tensiómetro de brazo inalámbrico todo en uno con Bluetooth.',              89.99, 'salud', '💊',   NULL,         35, 4.50, 543),
('Withings Thermo',           'Termómetro temporal sin contacto con historial familiar en app.',          99.99, 'salud', '🌡️',  NULL,         40, 4.30, 267),
('Ultrahuman Ring Air',       'Anillo de titanio con monitoreo metabólico y score de movimiento.',       349.99, 'salud', '💍',   'nuevo',      18, 4.50, 312),
('Eight Sleep Pod 4',         'Cubierta de colchón con regulación de temperatura por IA.',               2299.99,'salud', '🛏️',  'bestseller',  8, 4.70, 634),
('ResMed AirSense 11',        'CPAP inteligente con AutoRamp y detección de apnea del sueño.',           849.99, 'salud', '😪',   NULL,         12, 4.60, 389),
('Withings Sleep Analyzer',   'Almohadilla bajo el colchón que rastrea apnea y ciclos de sueño.',        129.99, 'salud', '🌙',   NULL,         22, 4.40, 287),
('Halo Rise',                 'Despertador inteligente que rastrea el sueño con radar sin contacto.',    139.99, 'salud', '☀️',   'nuevo',      20, 4.30, 198),
('COROS PACE 3',              'GPS de running ultraligero con análisis de lactato y potencia.',           229.99, 'salud', '🏅',   NULL,         18, 4.70, 423),
('Suunto Race',               'Reloj multideporte con mapas topográficos y análisis de entrenamiento.',  449.99, 'salud', '⛰️',  NULL,         10, 4.60, 234),
('Polar Ignite 3',            'Reloj de fitness con guía de entrenamiento diaria personalizada por IA.', 299.99, 'salud', '🔥',   NULL,         15, 4.50, 312),
('Fitbit Sense 2',            'Reloj de salud con sensor EDA para gestión del estrés y bienestar.',      249.99, 'salud', '😌',   'descuento',  20, 4.40, 489),
('Amazfit GTR 4',             'Smartwatch con análisis de composición corporal e IA de salud.',          199.99, 'salud', '⚡',   NULL,         25, 4.50, 567),
('Amazfit Balance',           'Reloj con coaching de salud Zepp AI y análisis de bienestar integral.',   249.99, 'salud', '⚖️',  'nuevo',      20, 4.60, 389),
('RingConn Smart Ring',       'Anillo inteligente con monitoreo continuo de salud y 9 días de batería.', 279.99, 'salud', '💫',   NULL,         15, 4.50, 234),
('Masimo W1',                 'Wearable médico con SpO2 continuo, frecuencia cardíaca y temperatura.',   599.99, 'salud', '🩻',   NULL,          8, 4.70, 156),
('Nix Hydration Biosensor',   'Parche que mide electrolitos en el sudor durante el ejercicio.',          129.99, 'salud', '💧',   'nuevo',      30, 4.40, 198),
('Polar H10',                 'Sensor de frecuencia cardíaca de pecho con mayor precisión del mercado.',  89.99, 'salud', '❤️‍🔥','bestseller', 40, 4.80, 987),
('Wahoo TICKR X',             'Monitor cardíaco con análisis de cadencia y métricas de carrera.',         79.99, 'salud', '🏃‍♂️',NULL,         35, 4.60, 678),
('Garmin HRM-Pro Plus',       'Banda pectoral con métricas avanzadas de carrera, ciclismo y natación.',  129.99, 'salud', '🏊',   NULL,         28, 4.70, 534),
('Withings Move ECG',         'Reloj híbrido analógico con ECG y seguimiento de actividad 24/7.',        199.99, 'salud', '🕐',   NULL,         18, 4.40, 287),
('Biostrap EVO',              'Pulsera clínica con análisis de HRV y calidad de sueño profundo.',        179.99, 'salud', '📊',   NULL,         12, 4.40, 189),
('Dreem 3',                   'Diadema neurotecnológica para mejorar el sueño con estimulación sonora.', 549.99, 'salud', '🧠',   NULL,          6, 4.30, 112),
('Oxiline Pulse X Pro',       'Pulsioxímetro de dedo con pantalla OLED y conectividad Bluetooth.',        49.99, 'salud', '🔵',   NULL,         50, 4.50, 634),
('Masimo MightySat',          'Pulsioxímetro médico con índice de perfusión y variabilidad respiratoria.',199.99,'salud', '💙',   NULL,         15, 4.60, 312),
('Theragun Prime',            'Masajeador de percusión con 5 cabezales y guía de recuperación por IA.',  299.99, 'salud', '💪',   'bestseller', 25, 4.70, 1243),
('Hypervolt Go 2',            'Masajeador de percusión portátil con 3 velocidades y 3 horas de batería.',179.99, 'salud', '⚡',   NULL,         20, 4.50, 567),
('Compex Sport Elite',        'Electroestimulador muscular con 32 programas personalizados por IA.',     399.99, 'salud', '🔌',   NULL,         10, 4.50, 234),
('Normatec 3 Legs',           'Botas de compresión neumática con IA para recuperación deportiva.',       899.99, 'salud', '🦵',   'bestseller', 12, 4.80, 789),
('PowerDot 2.0',              'Electroestimulador inalámbrico con app de entrenamiento y recuperación.', 229.99, 'salud', '⚡',   NULL,         18, 4.50, 312),
('Kinsa QuickCare',           'Termómetro conectado con diagnóstico basado en IA y guía de síntomas.',    39.99, 'salud', '🤒',   NULL,         60, 4.40, 876),
('Omron Complete Watch',      'Reloj que mide presión arterial y ECG de forma simultánea con IA.',       399.99, 'salud', '⌚',   'nuevo',      10, 4.60, 187),
('Whoop 4.0',                 'Banda sin pantalla con análisis de recuperación y strain por IA.',        239.99, 'salud', '🏋️',  'bestseller', 35, 4.70, 1567),
('Perifit Care+',             'Dispositivo Kegel con biofeedback y juegos terapéuticos para suelo pélvico.',119.99,'salud','🌸', 'nuevo',      20, 4.50, 312),
('Elvie Trainer',             'Entrenador Kegel inteligente con seguimiento de progreso en app.',        199.99, 'salud', '🌷',   NULL,         15, 4.40, 267),
('Beurer BF 950',             'Báscula médica con análisis corporal detallado y app de salud familiar.', 89.99, 'salud',  '🧬',   NULL,         30, 4.30, 445),
('Garmin Index S2',           'Báscula inteligente Wi-Fi con reconocimiento de usuario y análisis BMI.', 149.99, 'salud', '📏',   NULL,         22, 4.50, 389),
('Wyze Scale X',              'Báscula smart con 12 métricas corporales y compatibilidad con Fitbit.',    39.99, 'salud', '⚖️',  'descuento',  40, 4.40, 1234),
('Withings Body+',            'Báscula Wi-Fi con análisis de grasa, músculo y agua corporal por IA.',     99.99, 'salud', '💪',   'bestseller', 35, 4.60, 876),

-- ============================================================
-- BELLEZA (50)
-- ============================================================
('HiMirror Mini X',          'Espejo inteligente con análisis de piel por IA y recomendaciones.',        199.99, 'belleza', '🪞',  'bestseller', 22, 4.60, 398),
('FOREO LUNA 4',             'Limpiador facial con IA que adapta la intensidad a tu tipo de piel.',      219.99, 'belleza', '🫧',  NULL,         16, 4.70, 521),
('Dyson Airwrap i.d.',       'Multiestilarizador que ajusta el calor según el tipo de cabello.',         599.99, 'belleza', '🪮',  'descuento',   9, 4.80, 632),
('NuFace Trinity+',          'Dispositivo de microcorriente facial para tonificar y reafirmar la piel.', 339.99, 'belleza', '💆',  NULL,         11, 4.50, 274),
('FOREO BEAR 2',             'Dispositivo de microcorriente con tecnología anti-shock y app de IA.',     299.99, 'belleza', '⚡',  'nuevo',      14, 4.60, 312),
('CurrentBody Skin LED Mask','Mascarilla LED de 132 luces para estimular colágeno y rejuvenecimiento.',  380.00, 'belleza', '💡',  'bestseller', 18, 4.70, 543),
('Theraface Pro',            'Herramienta facial multipropósito con percusión y microcorriente.',        399.99, 'belleza', '✨',  NULL,         12, 4.60, 289),
('Nira Precision Laser',     'Láser antienvejecimiento doméstico para reducir líneas de expresión.',     199.99, 'belleza', '🔬',  NULL,         10, 4.50, 178),
('Déesse Pro LED Mask',      'Mascarilla LED profesional con 9 tipos de luz y app conectada.',          1900.00, 'belleza', '🎭',  NULL,          5, 4.60, 89),
('LightStim for Wrinkles',   'Panel LED multiondas con efectividad clínica para reducir arrugas.',       249.00, 'belleza', '💛',  NULL,         15, 4.50, 234),
('Silk''n Titan',            'Dispositivo de reafirmación con energía bipolar, IR y luz intensa.',      299.99, 'belleza', '🌟',  NULL,         12, 4.40, 198),
('Ulike Air3',               'Depiladora IPL con tecnología Sapphire Ice-Cooling sin dolor.',            329.99, 'belleza', '❄️',  'bestseller', 20, 4.70, 876),
('Braun Silk-expert Pro 5',  'Depiladora IPL con sensor de tono de piel para máxima eficacia.',         399.99, 'belleza', '🌸',  NULL,         15, 4.60, 567),
('Philips Lumea Prestige',   'Depiladora IPL con 4 cabezales y app de guía personalizada.',             449.99, 'belleza', '🌺',  NULL,         12, 4.70, 634),
('SmoothSkin Pure Fit',      'IPL inalámbrico con modo automático y sensor de tono de piel.',           349.99, 'belleza', '🌷',  NULL,         14, 4.50, 312),
('Dyson Supersonic r',       'Secador de cabello con motor V9 e inteligencia de temperatura adaptativa.',499.99, 'belleza', '💨',  'bestseller', 18, 4.80, 1123),
('Shark FlexStyle',          'Estilizador multifunción para secar y peinar en un solo aparato.',         299.99, 'belleza', '🌀',  NULL,         16, 4.60, 489),
('GHD Chronos',              'Plancha con predicción de calor y tecnología de ultra-deslizamiento.',     279.99, 'belleza', '〰️', 'nuevo',      10, 4.70, 312),
('BaByliss Curl Secret',     'Rizador automático con aspiración e IA para ondas perfectas sin esfuerzo.',249.99, 'belleza', '💇',  NULL,         12, 4.50, 267),
('Remington Hydraluxe Pro',  'Plancha con placas de agua para protección máxima del cabello.',           149.99, 'belleza', '💧',  NULL,         20, 4.40, 345),
('FOREO ISSA 3',             'Cepillo dental de silicona con estimulación sónica y temporizador IA.',    199.99, 'belleza', '🦷',  'bestseller', 25, 4.60, 678),
('Oral-B iO Series 9',       'Cepillo eléctrico con reconocimiento de zonas y presión inteligente.',    249.99, 'belleza', '🪥',  NULL,         20, 4.70, 923),
('Philips Sonicare DiamondClean','Cepillo ultrasónico con 5 modos y app de análisis de higiene dental.',219.99, 'belleza', '💎',  NULL,         18, 4.60, 756),
('Oclean X Pro Elite',       'Cepillo sónico con pantalla táctil y detección de zona en tiempo real.',   99.99, 'belleza', '📱',  NULL,         22, 4.50, 412),
('Solawave Wand 4-en-1',     'Varita con luz roja, microcorriente, calor y vibración para la piel.',    169.00, 'belleza', '🌈',  'bestseller', 28, 4.70, 834),
('Medicube Age-R Booster Pro','Dispositivo coreano de alta frecuencia para renovación y firmeza celular.',299.99,'belleza', '🔮',  'nuevo',      10, 4.60, 234),
('PMD Clean Pro',            'Limpiador facial con vibración sónica y luz LED para combatir el acné.',   149.00, 'belleza', '💠',  NULL,         18, 4.50, 389),
('NuDerma Professional',     'Varita de alta frecuencia para tratar acné, manchas y ojeras.',             69.99, 'belleza', '⚡',  'descuento',  30, 4.30, 567),
('Ziip Halo',                'Dispositivo de nanocorriente con app de tratamientos faciales por IA.',    495.00, 'belleza', '🔆',  NULL,          8, 4.60, 178),
('Geneo+ Hydra',             'Sistema de oxigenación facial con limpieza y nutrición profunda.',         249.99, 'belleza', '🌊',  NULL,         10, 4.50, 156),
('NEWA Skin',                'Dispositivo de radiofrecuencia para reafirmar mejillas y cuello en casa.', 279.00, 'belleza', '🌿',  NULL,         12, 4.40, 198),
('TriPollar STOP VX2',       'Radiofrecuencia cuádruple para reducción de grasa y firmeza cutánea.',     599.00, 'belleza', '💪',  NULL,          8, 4.50, 145),
('Omnilux Contour Face',     'Mascarilla LED flexible de uso clínico para firma y rejuvenecimiento.',    395.00, 'belleza', '🌕',  NULL,         10, 4.70, 267),
('Joovv Solo 3.0',           'Panel de terapia de luz roja e infrarroja para regeneración profunda.',    599.00, 'belleza', '🔴',  NULL,          8, 4.60, 189),
('Baby Quasar MD Plus',      'Dispositivo de luz roja cuádruple para rejuvenecimiento facial en casa.',  399.00, 'belleza', '🔦',  NULL,         10, 4.50, 156),
('ReFa CARAT RAY Face',      'Rodillo de cuarzo con microcorriente japonesa para drenaje y lifting.',    249.00, 'belleza', '💜',  'bestseller', 20, 4.70, 712),
('COSBEAUTY Blackhead Vacuum','Aspirador de puntos negros con cámara IA y 4 cabezales intercambiables.',  59.99, 'belleza', '🔵',  NULL,         35, 4.30, 567),
('Tria Beauty Laser 4X',     'Láser de diodo doméstico para depilación permanente certificada.',         449.00, 'belleza', '💥',  NULL,         10, 4.50, 234),
('Kenzzi IPL Handset',       'Depiladora IPL con 6 niveles de intensidad y tratamiento de 10 minutos.',  169.99, 'belleza', '✨',  'descuento',  18, 4.40, 345),
('FOREO PEACH 2',            'Depiladora IPL con detección de tono de piel y guía inteligente en app.', 299.00, 'belleza', '🍑',  NULL,         12, 4.60, 289),
('Lustre ClearSkin',         'Dispositivo LED azul para tratamiento del acné sin fármacos ni agujas.',    89.00, 'belleza', '💙',  NULL,         20, 4.40, 312),
('Myotone Facial Toner',     'Tónico de microcorriente portátil para definir y tonificar el contorno.',   89.99, 'belleza', '⚡',  'nuevo',      22, 4.40, 234),
('Colorup AI Nail Printer',  'Impresora de uñas que diseña y aplica arte único con IA en segundos.',     299.99, 'belleza', '💅',  'nuevo',      10, 4.30, 156),
('Selfie Leslie LED Mask',   'Mascarilla LED de 7 colores con vibración y terapia de calor combinada.',   99.99, 'belleza', '😊',  'nuevo',      25, 4.30, 267),
('Medi Lift EMS Face',       'Mascarilla de electroestimulación para lifting facial sin cirugía.',        359.00, 'belleza', '🏥',  NULL,          8, 4.50, 145),
('FOREO ESPADA 2',           'Varita de luz azul con microcorriente para tratamiento puntual del acné.', 149.00, 'belleza', '⚔️', NULL,         15, 4.40, 289),
('Hangsun Hair Analyzer',    'Microscopio Wi-Fi para analizar el cuero cabelludo y cabello con IA.',      79.99, 'belleza', '🔎',  NULL,         20, 4.30, 198),
('MYSA LED Mask',            'Mascarilla LED de 7 colores para acné, manchas y rejuvenecimiento.',       129.99, 'belleza', '🎨',  NULL,         18, 4.40, 312),
('NuFace Fix Device',        'Dispositivo de microcorriente compacto para suavizar líneas de expresión.',  99.99, 'belleza', '✨',  'nuevo',      20, 4.50, 356),
('Sensica Sensilight Pro',   'Depiladora IPL multifunción con tratamiento anti-aging integrado.',         399.99, 'belleza', '🌟',  NULL,         10, 4.50, 178),

-- ============================================================
-- HOGAR (50)
-- ============================================================
('Roborock S8 MaxV',         'Robot aspirador con brazo robótico y reconocimiento de objetos por IA.',   799.99, 'hogar', '🤖',   'bestseller', 18, 4.80, 743),
('Nest Learning Thermostat', 'Termostato que aprende tu rutina y optimiza el consumo energético.',       249.99, 'hogar', '🌡️',  NULL,         25, 4.70, 512),
('Arlo Ultra 2',             'Cámara 4K con detección inteligente de personas y vehículos.',             199.99, 'hogar', '📷',   'descuento',  20, 4.50, 334),
('Eufy Smart Lock S330',     'Cerradura con reconocimiento facial y huella dactilar biométrica.',        299.99, 'hogar', '🔐',   'nuevo',      14, 4.60, 221),
('Sonos Era 300',            'Altavoz espacial con IA Dolby Atmos que adapta el sonido al espacio.',     449.99, 'hogar', '🎵',   NULL,         16, 4.70, 418),
('Amazon Echo Show 15',      'Pantalla inteligente de 15" con IA visual y control total del hogar.',     249.99, 'hogar', '📺',   'bestseller', 30, 4.60, 892),
('Google Nest Hub Max',      'Pantalla smart de 10" con reconocimiento facial y cámara Nest integrada.', 229.99, 'hogar', '🏠',   NULL,         25, 4.60, 634),
('Nanoleaf Lines',           'Líneas de luz modulares con detección de ritmo musical e IA de color.',    249.99, 'hogar', '🌈',   'bestseller', 22, 4.70, 567),
('August Wi-Fi Smart Lock',  'Cerradura smart con detección de llegada y bloqueo automático por IA.',    229.99, 'hogar', '🔑',   NULL,         18, 4.50, 423),
('Ring Video Doorbell Pro 2','Timbre con visión 3D y detección de movimiento por IA en tiempo real.',    249.99, 'hogar', '🔔',   'bestseller', 25, 4.70, 876),
('Nest Protect Smoke',       'Detector de humo y CO con voz inteligente, alertas y autotest automático.',119.99, 'hogar', '🔥',   NULL,         30, 4.70, 678),
('Ecobee SmartThermostat',   'Termostato con sensor de ocupación y análisis de consumo por IA.',        249.99, 'hogar', '🌿',   NULL,         20, 4.60, 512),
('iRobot Roomba j9+',        'Robot aspirador con vaciado automático y esquiva de obstáculos dinámico.', 899.99, 'hogar', '🤖',   'bestseller', 15, 4.80, 1124),
('Roborock Dyad Pro Combo',  'Aspiradora y trapeadora inalámbrica con tanque automix inteligente.',      499.99, 'hogar', '🧹',   'nuevo',      16, 4.60, 389),
('Ecovacs Deebot X2 Omni',   'Robot aspirador con estación de vaciado, lavado y secado automático.',    1099.99,'hogar', '🏅',   NULL,         10, 4.70, 567),
('Dyson 360 Vis Nav',        'Robot aspirador con visión 360° y el motor más potente de su categoría.', 999.99, 'hogar', '👁️',  NULL,          8, 4.70, 289),
('SwitchBot S10',            'Robot aspirador con llenado y vaciado automático de agua sin intervención.',899.99, 'hogar', '💧',   'nuevo',      12, 4.60, 234),
('Govee AI Gaming Light',    'Tira LED con cámara que replica los colores de la pantalla en tiempo real.',149.99, 'hogar', '🎮',   'bestseller', 28, 4.60, 892),
('LIFX Beam',                'Módulos de luz que crean efectos visuales con sincronización musical.',    199.99, 'hogar', '🌊',   NULL,         18, 4.50, 345),
('Philips Hue HDMI Sync Box','Sincroniza la televisión con las luces Hue para experiencia inmersiva.',   249.99, 'hogar', '📺',   NULL,         15, 4.60, 423),
('Aqara Door Sensor P2',     'Sensor de apertura con detección de vibración y alertas por IA.',          29.99, 'hogar', '🚪',   NULL,         50, 4.40, 567),
('SimpliSafe Home Security', 'Sistema de alarma inteligente con detección de intrusos por IA.',         299.99, 'hogar', '🛡️',  'bestseller', 20, 4.70, 1234),
('Arlo Pro 5S',              'Cámara exterior 2K con color nocturno y sirena activada por IA.',          199.99, 'hogar', '🌙',   NULL,         18, 4.60, 456),
('Reolink Argus 4 Pro',      'Cámara solar 4K con detección de personas y visión color las 24 horas.',  119.99, 'hogar', '☀️',   'nuevo',      22, 4.60, 389),
('Eufy SoloCam S340',        'Cámara solar con zoom óptico 8x y seguimiento de movimiento automático.',  149.99, 'hogar', '🔍',   NULL,         20, 4.50, 312),
('Wyze Cam OG',              'Cámara de seguridad con detección inteligente y plan Cam Plus gratuito.',   39.99, 'hogar', '📸',   'descuento',  40, 4.40, 1567),
('Moen Smart Faucet',        'Grifo inteligente con control de temperatura y dosis de agua exacta.',     349.99, 'hogar', '🚰',   NULL,         10, 4.50, 234),
('Eve Energy Smart Plug',    'Enchufe inteligente con medición de consumo en tiempo real y automáticas.',  39.99, 'hogar', '⚡',   NULL,         45, 4.50, 678),
('Kasa Smart Power Strip',   'Regleta inteligente con 6 enchufes individuales controlables por app.',     49.99, 'hogar', '🔌',   'bestseller', 35, 4.70, 1234),
('Lutron Caseta Dimmer',     'Interruptor atenuador smart compatible con Alexa, Google y Apple.',         59.99, 'hogar', '🏡',   NULL,         30, 4.70, 876),
('Samsung SmartThings Hub',  'Centro de hogar inteligente compatible con más de 200 marcas y protocolos.', 99.99,'hogar', '🌐',   NULL,         22, 4.40, 456),
('Meross Smart Garage Door', 'Controlador de puerta de garage con alertas y verificación por IA.',        39.99, 'hogar', '🚗',   NULL,         28, 4.50, 567),
('Chamberlain myQ Smart',    'Control de garage con cámara HD y compatibilidad con Amazon Key.',          99.99, 'hogar', '🏠',   NULL,         20, 4.40, 423),
('Netatmo Smart Camera',     'Cámara interior con reconocimiento facial de personas conocidas.',          299.99, 'hogar', '👤',   NULL,         15, 4.50, 312),
('Airthings Wave Plus',      'Monitor de calidad del aire con detección de radón, CO2 y VOCs.',          229.99, 'hogar', '🌡️',  NULL,         18, 4.50, 389),
('Awair Element',            'Sensor de calidad del aire interior con 5 factores y análisis por IA.',    149.99, 'hogar', '🌱',   'nuevo',      20, 4.50, 267),
('Govee Smart Air Purifier', 'Purificador con filtro HEPA y ajuste automático de velocidad por IA.',     199.99, 'hogar', '🫁',   NULL,         15, 4.50, 312),
('Winix 5500-2',             'Purificador de aire con PlasmaWave y modo automático de limpieza.',        199.99, 'hogar', '💨',   'bestseller', 20, 4.70, 1567),
('Levoit Core 400S',         'Purificador smart con sensor de partículas y modo ultra silencioso.',      149.99, 'hogar', '🌬️',  NULL,         22, 4.60, 789),
('Anova Precision Oven',     'Horno de vapor combinado con cocción sous vide integrada y IA.',           699.99, 'hogar', '🍳',   'nuevo',      8,  4.60, 312),
('June Oven',                'Horno con cámara interior y reconocimiento de alimentos por IA.',          599.99, 'hogar', '🥧',   NULL,         10, 4.50, 234),
('Tovala Smart Oven',        'Horno que escanea el código del producto y cocina automáticamente.',       399.99, 'hogar', '📱',   NULL,         12, 4.40, 189),
('GE Profile Smart Microwave','Microondas con scan-to-cook y control por Alexa integrado.',             219.99, 'hogar', '📡',   NULL,         15, 4.50, 312),
('Philips Hue Gradient Strip','Tira LED con gradiente de colores individuales por zonas de luz.',        179.99, 'hogar', '💡',   NULL,         20, 4.60, 456),
('LIFX Clean',               'Bombilla con luz antibacteriana HEV y control por voz con IA.',            79.99, 'hogar', '🦠',   'nuevo',      30, 4.40, 234),
('Amazon Astro',             'Robot doméstico con IA que patrulla y envía alertas de seguridad.',       1599.99, 'hogar', '🤖',  'nuevo',       6, 4.20, 145),
('bObsweep PetHair Vision',  'Robot aspirador con cámara de seguridad integrada y IA de navegación.',   399.99, 'hogar', '🐾',   NULL,         12, 4.30, 267),
('WeMo Smart Dimmer',        'Interruptor atenuador inteligente con horarios y control por voz.',         44.99, 'hogar', '🌅',   NULL,         25, 4.40, 345),
('Eve Motion Sensor',        'Sensor de movimiento inteligente con análisis de patrones y privacidad.',   49.99, 'hogar', '🏃',   NULL,         30, 4.50, 389),
('Netatmo Weather Station',  'Estación meteorológica personal con análisis de tendencias por IA.',       179.99, 'hogar', '🌤️',  NULL,         15, 4.60, 456),

-- ============================================================
-- WEARABLES (50)
-- ============================================================
('Apple Watch Ultra 2',      'Smartwatch de titanio con chip S9, GPS dual y resistencia de expedición.', 799.99, 'wearables', '⌚', 'bestseller', 30, 4.90, 1240),
('Samsung Galaxy Ring',      'Anillo de titanio con seguimiento de salud y sueño por IA Samsung.',      399.99, 'wearables', '💍', 'nuevo',      20, 4.50, 287),
('Whoop 4.0 Band',           'Banda sin pantalla con análisis de recuperación, strain y sueño por IA.', 239.99, 'wearables', '🏋️','bestseller', 35, 4.70, 892),
('Garmin Fenix 7X Pro',      'Reloj outdoor con mapas TopoActive, potencia de carrera y carga solar.',  849.99, 'wearables', '🗺️',NULL,         12, 4.80, 567),
('Ray-Ban Meta Glasses',     'Gafas con asistente Meta AI, cámara 12MP y audio abierto integrado.',     299.99, 'wearables', '🕶️','nuevo',      18, 4.40, 312),
('Apple Watch Series 9',     'Reloj con chip S9 SiP y gesto de doble toque para control sin manos.',    399.99, 'wearables', '⌚', 'bestseller', 40, 4.80, 2134),
('Samsung Galaxy Watch 6 Classic','Bisel físico giratorio con análisis avanzado de composición corporal.',399.99,'wearables','🔄',NULL,         15, 4.60, 678),
('Garmin Forerunner 965',    'GPS multisport con pantalla AMOLED y métricas de Training Readiness.',    599.99, 'wearables', '🏃', 'bestseller', 18, 4.80, 934),
('Fitbit Versa 4',           'Reloj con GPS integrado, análisis de sueño y más de 40 modos de ejercicio.',199.99,'wearables','🌙',NULL,         22, 4.40, 567),
('Amazfit Falcon',           'Reloj de titanio con IA de entrenamiento y 20 días de batería.',          499.99, 'wearables', '🦅', NULL,         10, 4.60, 234),
('Huawei Watch GT 4',        'Reloj elegante con ECG, SpO2 y análisis de salud femenina avanzado.',     299.99, 'wearables', '💚', NULL,         15, 4.50, 389),
('Xiaomi Watch S3',          'Smartwatch con bisel intercambiable y chip de salud avanzado.',           199.99, 'wearables', '🌟', 'nuevo',      20, 4.40, 312),
('Withings ScanWatch Horizon','Reloj de buceo con ECG, SpO2 y diseño náutico premium.',                 499.99, 'wearables', '⚓', NULL,          8, 4.60, 189),
('Suunto Vertical',          'Reloj de aventura con mapa de ruta y IA de aclimatación a la altitud.',   699.99, 'wearables', '🏔️',NULL,         10, 4.60, 178),
('COROS VERTIX 2S',          'Reloj de expedición con GPS dual y batería de 60 horas de uso GPS.',      699.99, 'wearables', '🧭', 'nuevo',      8,  4.70, 212),
('Polar Grit X2 Pro',        'Reloj de trail running con mapa topográfico y recuperación de carga.',    499.99, 'wearables', '🌲', NULL,         10, 4.70, 234),
('Garmin epix Pro Gen 2',    'Smartwatch AMOLED multisport con sensor de profundidad y escalada.',      899.99, 'wearables', '🧗', 'bestseller', 12, 4.80, 567),
('Meta Quest 3',             'Headset de realidad mixta con IA de reconocimiento del entorno en HD.',   499.99, 'wearables', '🥽', 'bestseller', 25, 4.70, 1234),
('Apple Vision Pro',         'Computadora espacial con visionOS y control por mirada y gestos.',       3499.99, 'wearables', '🔮', 'nuevo',       5, 4.60, 456),
('Humane AI Pin',            'Pin de IA proyectable con asistente integrado que no requiere smartphone.',699.99, 'wearables', '📌', 'nuevo',      10, 4.00, 234),
('Sony WH-1000XM5',          'Auriculares con cancelación de ruido líder en industria y IA de voz.',   349.99, 'wearables', '🎵', 'bestseller', 30, 4.80, 2456),
('Bose QuietComfort Ultra',  'Auriculares con Immersive Audio espacial y cancelación adaptativa.',      429.00, 'wearables', '🔇', 'bestseller', 25, 4.80, 1678),
('Apple AirPods Pro 2',      'Auriculares con chip H2, cancelación adaptativa y Conversation Awareness.',249.00,'wearables','🍎','bestseller',  40, 4.80, 3456),
('Samsung Galaxy Buds3 Pro', 'Auriculares con IA de adaptación de sonido y cancelación inteligente.',  249.99, 'wearables', '💎', NULL,         20, 4.60, 567),
('Jabra Evolve2 85',         'Auriculares profesionales con 6 micrófonos y IA para conferencias.',      379.99, 'wearables', '💼', NULL,         15, 4.70, 423),
('Google Pixel Watch 3',     'Smartwatch con Fitbit avanzado y IA de respuestas predictivas integrada.',349.99, 'wearables', '🌀', 'nuevo',      18, 4.50, 456),
('Garmin Venu 3S',           'Reloj de fitness AMOLED con modo accesibilidad y silla de ruedas.',      399.99, 'wearables', '🌺', NULL,         12, 4.60, 312),
('Garmin Instinct 2X Solar', 'Reloj táctico con batería solar ilimitada y GPS multibanda.',             449.99, 'wearables', '☀️', 'bestseller', 20, 4.70, 789),
('Suunto 9 Peak Pro',        'Reloj de titanio ultradelgado con 300 horas de GPS y análisis de carrera.',649.99,'wearables','⛰️',NULL,         10, 4.60, 267),
('Oura Ring Heritage',       'Anillo de titanio con guía de actividad diaria personalizada por IA.',   299.99, 'wearables', '💍', 'bestseller', 25, 4.70, 1123),
('Movano Evie Ring',         'Anillo de salud diseñado para mujeres con ciclo menstrual y HRV.',       269.99, 'wearables', '🌸', 'nuevo',      15, 4.40, 178),
('Ultrahuman Ring Air',      'Anillo de titanio con métricas de metabolismo, actividad y recuperación.',349.99, 'wearables', '💫', 'bestseller', 18, 4.60, 456),
('Garmin Vivomove Sport',    'Reloj híbrido con manecillas analógicas y pantalla OLED táctil oculta.', 199.99, 'wearables', '🕐', NULL,         15, 4.50, 312),
('Fitbit Inspire 3',         'Pulsera delgada con sensor de estrés, SpO2 y 10 días de batería.',        99.99, 'wearables', '💚', NULL,         30, 4.50, 1234),
('Fossil Gen 6 Wellness',    'Smartwatch Wear OS con sensores de salud avanzados y carga rápida.',     249.99, 'wearables', '⌚', 'descuento',  15, 4.30, 389),
('TAG Heuer Connected E4',   'Smartwatch de lujo en titanio con Wear OS y bisel cerámico.',            1650.00, 'wearables', '💎', NULL,          5, 4.60, 145),
('Montblanc Summit 3',       'Smartwatch premium en titanio con Wear OS y sensor cardíaco óptico.',    1050.00, 'wearables', '🏔️',NULL,          5, 4.50, 112),
('Garmin Lily 2',            'Reloj de fitness elegante para mujer con cristal estampado y GPS.',      249.99, 'wearables', '🌸', NULL,         18, 4.60, 456),
('Amazfit T-Rex Ultra',      'Reloj militar MIL-STD-810H con GPS dual y profundidad de 100 metros.',   449.99, 'wearables', '🦖', NULL,         12, 4.60, 312),
('Casio G-Shock GBD-H2000',  'Reloj deportivo con GPS integrado, SpO2 y análisis de actividad.',       399.99, 'wearables', '💥', NULL,         10, 4.50, 234),
('Ticwatch Pro 5',           'Wear OS con chip Snapdragon W5+ y monitoreo de salud las 24 horas.',    299.99, 'wearables', '⏱️', NULL,         15, 4.40, 289),
('Nothing Ear (2)',          'Auriculares con ANC personalizado y IA de adaptación de sonido.',         149.99, 'wearables', '🎧', NULL,         22, 4.50, 567),
('Dyson Zone Headphones',    'Auriculares con purificador de aire integrado y cancelación activa.',     949.99, 'wearables', '🎧', NULL,          8, 4.40, 189),
('OPPO Watch 4 Pro',         'Smartwatch Android con ECG, potencia ciclista y carga ultra rápida.',    349.99, 'wearables', '⚡', NULL,         12, 4.40, 234),
('McLear RingPay 2',         'Anillo de pago sin contacto resistente al agua con tecnología NFC.',     129.99, 'wearables', '💳', 'nuevo',      20, 4.30, 156),
('Noise ColorFit Ultra 3',   'Smartwatch con IA Noise Health Suite, AMOLED y batería de 7 días.',       89.99, 'wearables', '🌈', NULL,         25, 4.30, 456),
('Garmin Forerunner 265',    'GPS de running con AMOLED y métricas de Morning Report por IA.',         449.99, 'wearables', '🏃', NULL,         15, 4.70, 567),
('Samsung Galaxy Watch 6',   'Smartwatch con análisis de sueño avanzado y sensor de composición.',     299.99, 'wearables', '⌚', NULL,         20, 4.60, 789),
('Jabra Enhance Plus',       'Audífonos discretos con IA de mejora del habla y ANC adaptativo.',       799.99, 'wearables', '👂', 'nuevo',       8, 4.50, 112),
('Skagen Falster Gen 6',     'Smartwatch escandinavo minimalista con Wear OS y sensor de SpO2.',       249.99, 'wearables', '🌿', 'descuento',  10, 4.30, 234),

-- ============================================================
-- MASCOTAS (50)
-- ============================================================
('Halo Collar 3',            'Collar GPS con valla virtual invisible entrenada por IA para perros.',    499.99, 'mascotas', '🐾',  'bestseller', 14, 4.70, 423),
('Litter-Robot 4',           'Arenero autolimpiante con monitoreo de salud felina por IA integrada.',   699.99, 'mascotas', '🐱',  NULL,         10, 4.80, 634),
('Furbo 360 Dog Camera',     'Cámara rotatoria con IA de seguimiento y lanzador automático de premios.', 169.99, 'mascotas', '🐶',  'descuento',  22, 4.60, 512),
('Petcube Bites 2',          'Cámara con IA que detecta ladridos y lanza premios automáticamente.',      99.99, 'mascotas', '📡',  'nuevo',      28, 4.40, 287),
('Tractive GPS Dog 4',       'GPS en tiempo real con análisis de actividad y zonas seguras por IA.',     49.99, 'mascotas', '🐕',  NULL,         40, 4.50, 398),
('Whistle Go Explore',       'Collar GPS con análisis de comportamiento y salud predictiva.',            79.99, 'mascotas', '📍',  'bestseller', 30, 4.60, 634),
('Fi Series 3 Smart Collar', 'Collar GPS con detección de escape automática y análisis de sueño.',     149.99, 'mascotas', '🔍',  'nuevo',      22, 4.60, 312),
('PetPace Smart Collar',     'Collar médico con ECG canino, temperatura y monitoreo de actividad 24/7.',299.99, 'mascotas', '🩺',  NULL,          8, 4.60, 189),
('Sure Petcare Microchip Feeder','Comedero con lector de microchip que niega acceso a otras mascotas.', 199.99, 'mascotas', '🍽️', NULL,         15, 4.60, 312),
('PetSafe Smart Feed 2.0',   'Comedero automático Wi-Fi con control de porciones y horarios por app.',  149.99, 'mascotas', '🥣',  'bestseller', 25, 4.60, 789),
('PETLIBRO Automatic Feeder','Comedero de 5 litros con app y sensor de atasco automático integrado.',    89.99, 'mascotas', '🐈',  'nuevo',      30, 4.50, 456),
('SureFeed Microchip Feeder','Comedero con tapa hermética activada por microchip del animal.',          199.99, 'mascotas', '🔒',  NULL,         18, 4.60, 345),
('Invoxia Pet Tracker',      'GPS sin suscripción mensual con batería de 60 horas y alertas de zona.',   99.99, 'mascotas', '📶',  NULL,         20, 4.40, 267),
('PetFon Pet GPS Tracker',   'GPS en tiempo real sin tarifa mensual con modo seguimiento activo.',       79.99, 'mascotas', '🛰️', 'nuevo',      22, 4.30, 198),
('Catit PIXI Smart',         'Sistema modular inteligente de fuentes y comederos para gatos con app.',  149.99, 'mascotas', '🌊',  NULL,         15, 4.50, 234),
('PetSafe Drinkwell Avalon', 'Fuente bebedero automática con filtro de carbón activo y flujo silencioso.',59.99,'mascotas', '💦',  'bestseller', 35, 4.60, 892),
('CleverPet Hub',            'Consola de juegos interactiva para perros con desafíos de IA cognitiva.', 299.99, 'mascotas', '🎮',  NULL,          8, 4.40, 167),
('iFetch Ball Launcher',     'Lanzador automático de pelotas con 3 distancias para perros activos.',    115.00, 'mascotas', '⚽',  'bestseller', 20, 4.60, 789),
('Wickedbone Smart Bone',    'Hueso interactivo con control remoto y modos de juego autónomo por IA.',   89.99, 'mascotas', '🦴',  NULL,         18, 4.40, 312),
('Petronics Mousr',          'Ratón robótico con IA que imita el comportamiento real para estimular gatos.',79.99,'mascotas','🖱️',NULL,         20, 4.50, 267),
('PetSafe Bolt Laser',       'Juguete láser automático con patrones aleatorios para estimular gatos.',   29.99, 'mascotas', '🔴',  NULL,         40, 4.40, 567),
('Cheerble Wicked Ball',     'Pelota interactiva autónoma con 3 modos de actividad controlados por IA.',  49.99,'mascotas','⚡',  NULL,         30, 4.40, 423),
('Furbo Dog Nanny',          'Sistema de monitoreo con IA que envía alertas de comportamiento canino.', 249.99, 'mascotas', '🎯',  'nuevo',      12, 4.60, 267),
('Pawbo+ Smart Pet Camera',  'Cámara con juego láser integrado y dispensador de premios remotos.',       99.99, 'mascotas', '🎪',  NULL,         18, 4.40, 234),
('Petcube Play 2',           'Cámara 1080p con juego láser y detección de sonido para mascotas.',       149.99, 'mascotas', '🐾',  NULL,         15, 4.50, 312),
('Link AKC Smart Collar',    'Collar con GPS, temperatura ambiental y seguimiento de actividad.',        99.99, 'mascotas', '🌡️', NULL,         20, 4.30, 234),
('Garmin T5 GPS Dog Collar', 'Collar GPS para perros de caza con rango extendido y resistencia.',       299.99, 'mascotas', '🎯',  NULL,         10, 4.60, 189),
('SportDOG GPS Tracker',     'Rastreador para múltiples perros con rango de 15 km sin suscripción.',    249.99, 'mascotas', '🏕️', NULL,         12, 4.50, 167),
('PitPat Dog GPS',           'GPS ultraligero con plan de actividad diario personalizado por IA.',        69.99, 'mascotas', '🏃',  'nuevo',      22, 4.40, 234),
('Litter-Robot 3 Connect',   'Arenero autolimpiante con app, notificaciones de uso y control remoto.',  499.99, 'mascotas', '🐱',  'descuento',  12, 4.60, 876),
('CatGenie 120+',            'Arenero que se lava automáticamente conectado a la plomería del hogar.',  399.99, 'mascotas', '🚿',  NULL,          8, 4.40, 345),
('PetSafe ScoopFree Ultra',  'Arenero automático con bandeja desechable y contador de usos por IA.',    189.99, 'mascotas', '🧹',  NULL,         15, 4.50, 456),
('iRobot Roomba j7+ Pet',    'Robot aspirador con reconocimiento inteligente de residuos de mascotas.', 649.99, 'mascotas', '🤖',  'bestseller', 18, 4.70, 923),
('Varram Pet Fitness Robot', 'Robot de fitness para mascotas con dispensador de premios y app.',         99.99, 'mascotas', '🎲',  NULL,         20, 4.30, 234),
('GoBone Interactive Bone',  'Hueso motorizado con app y 12 patrones de movimiento para perros.',        79.99, 'mascotas', '🦴',  NULL,         18, 4.40, 189),
('PurrSong LavvieBot S',     'Arenero autolimpiante para múltiples gatos con app de monitoreo de salud.',499.99,'mascotas','🐈‍⬛','nuevo',      8,  4.60, 178),
('Petzi Treat Cam',          'Dispensador remoto de premios con cámara HD y audio bidireccional.',        79.99, 'mascotas', '📹',  NULL,         20, 4.30, 267),
('Waggle Pet Monitor',       'Monitor de temperatura de automóvil para mascotas con alerta SMS.',        59.99, 'mascotas', '🚗',  NULL,         25, 4.40, 312),
('PETKIT Pura Max',          'Arenero inteligente con detección de peso y análisis de salud por IA.',   449.99, 'mascotas', '🏥',  'nuevo',      10, 4.60, 234),
('Cube GPS Tracker',         'Rastreador GPS ultraligero para gatos con alerta de zona y app.',          39.99, 'mascotas', '📦',  'descuento',  30, 4.30, 345),
('Companion Smart Dog Toy',  'Juguete con IA que adapta el patrón de juego al nivel de energía del perro.',89.99,'mascotas','🎾','nuevo',       15, 4.40, 156),
('Animo Dog Activity Monitor','Monitor de actividad canina con reconocimiento de comportamientos.',       99.99, 'mascotas', '📊',  NULL,         18, 4.40, 267),
('Tailio Cat Health Monitor','Plataforma inteligente bajo el arenero que monitorea el peso y salud.',   149.99, 'mascotas', '⚖️', 'nuevo',      10, 4.50, 145),
('Petcube Care',             'Suscripción de monitoreo con historial de video y alertas IA de 30 días.',  39.99, 'mascotas', '☁️',  NULL,         40, 4.40, 456),
('Furbo Basic',              'Cámara para mascotas con audio bidireccional y lanzador de treats HD.',     69.99, 'mascotas', '🎥',  'descuento',  25, 4.50, 634),
('PetSafe Happy Rider',      'Cinturón de seguridad para mascotas con ajuste automático por talla.',      29.99, 'mascotas', '🚗',  NULL,         40, 4.30, 345),
('Baxter Robot Pet Sitter',  'Robot autónomo que entretiene, monitorea y alimenta mascotas solo.',       449.99, 'mascotas', '🤖',  'nuevo',       6, 4.30, 89),
('Wickedball Rechargeable',  'Pelota recargable con sensor de movimiento e IA de juego adaptativa.',     39.99, 'mascotas', '⚽',  NULL,         35, 4.40, 312),
('Motorola Peekaboo',        'Cámara de monitoreo de mascotas 1080p con visión nocturna y alertas.',     79.99, 'mascotas', '📷',  NULL,         20, 4.40, 234),

-- ============================================================
-- GADGETS (50)
-- ============================================================
('DJI Mini 4 Pro',           'Drone 4K con evitación omnidireccional y modo seguimiento por IA.',       759.99, 'gadgets', '🚁',  'bestseller', 15, 4.80, 678),
('Bambu Lab A1 Mini',        'Impresora 3D con calibración automática y detección de fallos por IA.',   299.99, 'gadgets', '🖨️', 'nuevo',      20, 4.70, 412),
('Plaud Note AI',            'Grabadora con IA que transcribe y resume reuniones al instante.',          159.99, 'gadgets', '📝',  'bestseller', 35, 4.60, 534),
('Elgato Wave DX',           'Micrófono dinámico con IA de filtrado de ruido ambiental en tiempo real.', 149.99, 'gadgets', '🎙️', NULL,         25, 4.50, 321),
('Timekettle WT2 Edge',      'Auriculares de traducción simultánea en 40 idiomas con IA.',              299.99, 'gadgets', '🌐',  'descuento',  18, 4.30, 243),
('DJI Osmo Pocket 3',        'Cámara de cardán 3 ejes con 4K/120fps y seguimiento facial por IA.',      519.99, 'gadgets', '📸',  'bestseller', 20, 4.80, 876),
('GoPro HERO13 Black',       'Cámara de acción con HyperSmooth 6.0 y estabilización por IA.',           399.99, 'gadgets', '🎬',  'bestseller', 25, 4.70, 1234),
('Insta360 X4',              'Cámara 360° de 8K con edición asistida por IA y modo invisible.',         499.99, 'gadgets', '🌐',  'nuevo',      15, 4.70, 567),
('DJI Action 4',             'Cámara de acción con sensor grande de 1/1.3" y RockSteady Ultra.',        399.99, 'gadgets', '🏄',  NULL,         18, 4.60, 456),
('Logitech MX Master 3S',    'Ratón ergonómico con desplazamiento MagSpeed y botón de IA dedicado.',      99.99, 'gadgets', '🖱️', 'bestseller', 30, 4.80, 2345),
('Logitech AI Keyboard',     'Teclado con tecla de prompt de IA dedicada y predicción de escritura.',    129.99, 'gadgets', '⌨️', 'nuevo',      22, 4.50, 456),
('Keychron Q1 Pro',          'Teclado mecánico inalámbrico con RGB y switches intercambiables en caliente.',199.99,'gadgets','⌨️',NULL,         18, 4.70, 567),
('Wacom Intuos Pro M',       'Tableta gráfica con lápiz Pro 2 sin batería y reconocimiento gestual.',   349.99, 'gadgets', '✏️', NULL,         12, 4.70, 789),
('XPPen Artist Pro 16',      'Monitor gráfico con pantalla QLED y lápiz X3 Pro de 16.000 niveles.',    499.99, 'gadgets', '🖥️', 'bestseller', 10, 4.70, 456),
('Bambu Lab P1S',            'Impresora 3D con carcasa cerrada, multifilamento y detección de errores.', 699.99, 'gadgets', '🔩',  NULL,          8, 4.80, 312),
('Prusa MK4',                'Impresora 3D open source con sensores de flujo y calibración automática.', 799.99, 'gadgets', '⚙️', NULL,         10, 4.80, 567),
('Elegoo Saturn 4 Ultra',    'Impresora de resina 12K con cámara de detección de fallas integrada.',    649.99, 'gadgets', '🌌',  NULL,          8, 4.60, 234),
('Creality K1 Max',          'Impresora 3D de alta velocidad 600mm/s con calibración LiDAR por IA.',    559.99, 'gadgets', '🚀',  'nuevo',      10, 4.60, 312),
('Jackery Explorer 1000 Pro','Generador solar portátil de 1002Wh con gestión inteligente de energía.',  999.99, 'gadgets', '☀️', 'bestseller', 12, 4.70, 892),
('EcoFlow DELTA 2',          'Estación de energía expansible con IA de optimización de carga y app.',   899.99, 'gadgets', '🔋',  'bestseller', 15, 4.80, 1234),
('Bluetti AC200MAX',         'Estación de poder de 2200W con doble entrada solar y batería expandible.', 1399.99,'gadgets', '💡',  NULL,          6, 4.70, 345),
('Goal Zero Yeti 1000X',     'Batería portátil Wi-Fi con gestión de consumo y carga solar integrada.', 1199.99, 'gadgets', '🏕️', NULL,          8, 4.60, 267),
('Anker 737 Power Bank',     'Batería de 24000mAh con pantalla digital y carga inteligente de 140W.',   149.99, 'gadgets', '📱',  'bestseller', 30, 4.70, 1567),
('Mophie Powerstation Pro',  'Batería portátil 20000mAh MagSafe con IA de distribución de carga.',      99.99, 'gadgets', '🔌',  NULL,         25, 4.50, 456),
('Samsung T9 Portable SSD',  'SSD externo 4TB ultraresistente IP65 con transferencia de 2000MB/s.',    249.99, 'gadgets', '💾',  NULL,         20, 4.70, 567),
('WD My Passport Ultra',     'Disco externo con encriptación automática por hardware y backup en nube.',  99.99, 'gadgets', '💽',  NULL,         30, 4.50, 789),
('Sandisk Extreme Pro V2',   'SSD portátil NVMe con 2000MB/s y protección de caídas de 2 metros.',     129.99, 'gadgets', '⚡',  NULL,         25, 4.70, 934),
('Ember Mug 2',              'Taza inteligente que mantiene la temperatura exacta hasta 80 minutos.',   149.95, 'gadgets', '☕',  'bestseller', 35, 4.80, 3456),
('Fellow Stagg EKG Pro',     'Kettle de café con control de temperatura al grado y temporizador.',      159.00, 'gadgets', '🫖',  NULL,         20, 4.70, 789),
('Meater Plus Thermometer',  'Termómetro inalámbrico para carnes con guía de cocción por IA en app.',    99.99, 'gadgets', '🌡️', 'bestseller', 30, 4.70, 2134),
('Ooni Volt 12',             'Horno de pizza eléctrico con control digital de temperatura por zonas.',  799.00, 'gadgets', '🍕',  'nuevo',       8, 4.70, 456),
('Anova Precision Cooker Pro','Sous vide Wi-Fi con guías de cocción personalizadas por IA integrada.',   199.00, 'gadgets', '🥩',  NULL,         18, 4.70, 1234),
('Apple AirTag',             'Rastreador de objetos con red Find My de millones de dispositivos Apple.',  29.99, 'gadgets', '🔍',  'bestseller', 60, 4.80, 8934),
('Samsung SmartTag2',        'Rastreador con UWB de precisión y 6 meses de batería sin reemplazo.',      29.99, 'gadgets', '🏷️', NULL,         50, 4.60, 1234),
('Tile Ultra',               'Rastreador Bluetooth con GPS integrado y red Find invisible de 500m.',     99.99, 'gadgets', '📍',  'nuevo',      30, 4.50, 567),
('Chipolo Card Spot',        'Rastreador con forma de tarjeta compatible con red Apple Find My.',        35.00, 'gadgets', '💳',  NULL,         40, 4.40, 345),
('Kindle Scribe',            'E-reader y cuaderno digital con pluma precisa y IA de resumen de notas.', 339.99, 'gadgets', '📖',  'bestseller', 25, 4.70, 2345),
('reMarkable 2',             'Tablet de papel digital con pluma de baja latencia y sincronización.',    299.00, 'gadgets', '✍️', NULL,         15, 4.60, 1234),
('Boox Note Air3 C',         'Tablet e-ink a color con Android 12 y soporte de apps externas.',         499.99, 'gadgets', '🎨',  'nuevo',      10, 4.60, 345),
('Onyx Boox Tab Ultra C Pro','Tablet e-ink 10.3" con OCR avanzado y anotaciones por IA integradas.',    599.99, 'gadgets', '📚',  NULL,          8, 4.60, 234),
('Rocketbook Core',          'Cuaderno reutilizable con OCR por app y sincronización a múltiples nubes.',  34.99, 'gadgets', '♻️', 'bestseller', 40, 4.60, 4567),
('Nuwa Pen Smart',           'Bolígrafo digital que digitaliza la escritura manuscrita en tiempo real.', 169.99, 'gadgets', '🖊️', 'nuevo',      15, 4.40, 234),
('Livescribe Symphony',      'Bolígrafo que graba audio sincronizado con la escritura a mano.',         149.99, 'gadgets', '📝',  NULL,         18, 4.50, 345),
('DJI Mini 3 Pro',           'Drone con cámara 4K HDR vertical y detección de obstáculos tri-direccional.',669.99,'gadgets','🚁','descuento',  12, 4.70, 789),
('Autel Evo Nano+',          'Drone 4K ultraligero de 249g con obstacle sensing y 28 minutos de vuelo.', 449.99, 'gadgets', '🚁',  NULL,         10, 4.50, 234),
('Skydio 2+',                'Drone con IA de seguimiento autónomo más avanzada del mercado.',           999.99, 'gadgets', '🤖',  NULL,          6, 4.60, 178),
('Anker EufyCam 3C',         'Cámara de seguridad solar 4K con almacenamiento local y IA de detección.', 299.99, 'gadgets', '📷', NULL,         15, 4.60, 456),
('NuPhy Air75 V2',           'Teclado inalámbrico ultradelgado con switches magnéticos de baja latencia.',149.99,'gadgets','💨',NULL,         12, 4.60, 312),
('Motorola Moto Tag',        'Rastreador compatible con Google Find My Device con batería de 1 año.',     24.99, 'gadgets', '📡',  'nuevo',      35, 4.30, 189),
('Espresso Display 17 Pro',  'Monitor portátil de 17" con touchscreen y IA de ajuste de pantalla.',     699.99, 'gadgets', '🖥️', 'nuevo',       8, 4.60, 156);
