-- ============================================================
-- conAI — 300 productos nuevas categorías (50 por categoría)
-- Ejecutar en Supabase > SQL Editor
-- NO hace TRUNCATE — agrega a los existentes
-- ============================================================

INSERT INTO products (name, description, price, category, icon, tag, stock, rating, review_count) VALUES

-- ============================================================
-- AUDIO INTELIGENTE (50)
-- ============================================================
('Sony WH-1000XM5',           'Auriculares inalámbricos con cancelación activa de ruido líder del mercado.',       349.99, 'audio', '🎧', 'bestseller', 25, 4.90, 4521),
('Apple AirPods Pro 2',       'Auriculares con chip H2, cancelación adaptativa y audio espacial personalizado.',   249.99, 'audio', '🍎', 'bestseller', 30, 4.80, 6234),
('Bose QuietComfort Ultra',   'Auriculares premium con modo inmersión y sonido espacial por IA.',                  429.99, 'audio', '🔇', 'bestseller', 20, 4.80, 3456),
('Samsung Galaxy Buds3 Pro',  'Earbuds con cancelación de ruido y audio 360 adaptativo por IA.',                  199.99, 'audio', '💎', 'nuevo',      28, 4.60, 1234),
('Jabra Evolve2 85',          'Auriculares de conferencia con 8 micrófonos y IA de voz para trabajo remoto.',     449.99, 'audio', '📞', NULL,         15, 4.70, 987),
('Bose SoundLink Max',        'Altavoz portátil resistente al agua con sonido 360° y ecualizador IA.',            399.99, 'audio', '🔊', 'bestseller', 18, 4.70, 2345),
('JBL Charge 6',              'Altavoz Bluetooth resistente al agua con 20h batería y bass turbo.',               149.99, 'audio', '💧', 'bestseller', 35, 4.70, 5678),
('Sony SRS-XB100',            'Altavoz compacto con sonido 360° y batería de 16 horas.',                          49.99, 'audio', '🎵', NULL,         40, 4.50, 2134),
('Bang & Olufsen Beosound A1','Altavoz premium con Bluetooth multipoint y diseño escandinavo icónico.',           279.99, 'audio', '🏆', NULL,         12, 4.80, 678),
('Harman Kardon Onyx Studio 8','Altavoz premium de sala con sonido estéreo dual y efectos IA.',                   349.99, 'audio', '🎼', NULL,         10, 4.70, 456),
('Sonos Era 100',             'Altavoz inteligente con Trueplay automático que se adapta a tu sala.',             249.99, 'audio', '🏠', 'bestseller', 20, 4.80, 3456),
('Sonos Move 2',              'Altavoz portátil con adaptación automática de sonido al entorno exterior.',        449.99, 'audio', '🌤️', NULL,         15, 4.80, 1567),
('Amazon Echo Studio',        'Altavoz inteligente con audio 3D y Alexa con respuestas por IA generativa.',      199.99, 'audio', '🌐', NULL,         22, 4.60, 2345),
('Apple HomePod mini',        'Altavoz inteligente con Siri, audio adaptativo y Hub del hogar integrado.',        99.99, 'audio', '🍏', NULL,         25, 4.60, 3456),
('Google Nest Audio',         'Altavoz inteligente con Google Assistant y calibración de sonido automática.',      99.99, 'audio', '🔵', NULL,         25, 4.50, 2134),
('Sonos Soundbar Arc Ultra',  'Barra de sonido con Dolby Atmos y calibración Trueplay por IA adaptativa.',       899.99, 'audio', '📺', 'bestseller', 10, 4.90, 1234),
('Samsung HW-Q990D',          'Barra de sonido 11.1.4 con audio espacial y modo SpaceFit Sound por IA.',         1299.99, 'audio', '🎬', NULL,          6, 4.80, 567),
('Bose Smart Soundbar 600',   'Barra de sonido con Dolby Atmos, voz Alexa y Google integrados.',                  399.99, 'audio', '🔉', 'descuento',  12, 4.70, 1234),
('LG SP9YA',                  'Barra de sonido 5.1.2 con Meridian y calibración de sala inteligente.',            349.99, 'audio', '🎶', NULL,         14, 4.60, 789),
('Denon DHT-S418',            'Soundbar con subwoofer inalámbrico y DTS Virtual:X para audio envolvente.',        299.99, 'audio', '🔈', NULL,         15, 4.60, 456),
('Shure MV7+',                'Micrófono USB/XLR con IA de supresión de ruido y mezcla por app.',                249.99, 'audio', '🎙️', 'bestseller', 20, 4.80, 1567),
('Blue Yeti X',               'Micrófono condensador con medidor LED inteligente y control por software.',        169.99, 'audio', '🎤', NULL,         18, 4.70, 2134),
('Rode NT-USB Mini',          'Micrófono compacto con IA de reducción de ruido de fondo en vivo.',               99.99, 'audio', '🎵', NULL,         22, 4.60, 987),
('DJI Mic 2',                 'Micrófono inalámbrico compacto con cancelación activa de ruido por IA.',          329.99, 'audio', '📡', 'nuevo',      15, 4.70, 678),
('Hollyland Lark M2',         'Micrófono lavalier inalámbrico con 8h batería y reducción de ruido IA.',          189.99, 'audio', '🎗️', NULL,         20, 4.60, 456),
('Sony WF-1000XM5',          'Earbuds premium con cancelación de ruido más avanzada en formato compacto.',       279.99, 'audio', '🔕', 'bestseller', 25, 4.80, 3456),
('Jabra Elite 10',            'Earbuds con sonido espacial MultiSensor y cancelación adaptativa de ruido.',       249.99, 'audio', '🌀', NULL,         20, 4.70, 1234),
('Sennheiser Momentum 4',     'Auriculares inalámbricos con adaptación automática al entorno auditivo.',          349.99, 'audio', '🎵', NULL,         15, 4.80, 987),
('Anker Soundcore Liberty 4', 'Earbuds con IA de adaptación de sonido y control de volumen espacial.',            99.99, 'audio', '💚', 'descuento',  30, 4.50, 2134),
('Nothing Ear (2)',            'Earbuds transparentes con cancelación personalizada y sonido Hi-Fi.',             149.99, 'audio', '⚪', NULL,         22, 4.60, 1567),
('Bose QuietComfort Earbuds 2','Earbuds con cancelación de ruido CustomTune personalizada por IA.',              279.99, 'audio', '🎧', 'bestseller', 20, 4.80, 2345),
('Technics EAH-AZ80',         'Earbuds premium con cancelación de ruido y LDAC para audio sin pérdidas.',        229.99, 'audio', '🎼', NULL,         15, 4.70, 678),
('Creative Outlier Pro+',     'Earbuds con certificación IP68, cancelación de ruido y codec aptX Lossless.',     129.99, 'audio', '💦', NULL,         25, 4.50, 345),
('Edifier TWS NB2 Pro',       'Earbuds con 6 micrófonos y cancelación activa de ruido de grado profesional.',    89.99, 'audio', '🎯', NULL,         30, 4.40, 567),
('Marshall Emberton III',     'Altavoz portátil con sonido 360° y batería de 30 horas impermeables.',           149.99, 'audio', '🎸', 'bestseller', 25, 4.80, 3456),
('Ultimate Ears Hyperboom',   'Altavoz de fiesta con bajo potente y adaptación automática de audio.',            399.99, 'audio', '🎉', NULL,         12, 4.70, 789),
('Tribit XSound Plus 2',      'Altavoz con sonido amplificado, IPX7 y tecnología BassUp por IA.',               49.99, 'audio', '🔋', NULL,         35, 4.50, 2345),
('Anker Soundcore Motion X600','Altavoz portátil con sonido espacial 50W y ajuste de agudos/graves por IA.',    89.99, 'audio', '🌊', 'nuevo',      28, 4.60, 1234),
('Bose Portable Smart Speaker','Altavoz inteligente con adaptación automática Bose SimpleSync en casa.',        299.99, 'audio', '🔊', NULL,         15, 4.70, 987),
('Devialet Phantom I',        'Altavoz con tecnología ADH y sonido de estudio en formato compacto.',           1590.00, 'audio', '👾', NULL,          5, 4.90, 234),
('Naim Mu-so Qb 2',           'Altavoz de red con DAC premium, AirPlay 2 y ecualización adaptativa.',           799.99, 'audio', '🎻', NULL,          6, 4.80, 189),
('Klipsch The One III',       'Altavoz Bluetooth con altavoces analógicos y tecnología Tractrix Horn.',         299.99, 'audio', '📻', NULL,         12, 4.70, 456),
('JBL PartyBox 310',          'Altavoz de fiesta 240W con luces LED sincronizadas y ecualizador DJ.',           349.99, 'audio', '🎊', NULL,         10, 4.60, 678),
('Sony SRS-XG500',            'Altavoz portátil premium con X-Balanced y batería de 30 horas de fiesta.',       349.99, 'audio', '⚡', 'descuento',  14, 4.60, 567),
('Bowers & Wilkins Px8',      'Auriculares premium con cuero genuino, IA adaptativa y aptX Adaptive.',          699.99, 'audio', '💼', NULL,           8, 4.90, 345),
('Sennheiser HD 560S',        'Auriculares abiertos de referencia con respuesta de frecuencia extendida.',       199.99, 'audio', '🎵', NULL,          12, 4.80, 789),
('Audio-Technica ATH-M50xBT2','Auriculares de monitoreo con Bluetooth y calidad de estudio inalámbrico.',       199.99, 'audio', '🎚️', NULL,         18, 4.70, 1234),
('Shure AONIC 50 Gen 2',      'Auriculares con cancelación ajustable y audio de estudio en calidad HD.',        379.99, 'audio', '🔬', NULL,          10, 4.70, 567),
('Master & Dynamic MW75',     'Auriculares con cancelación IA adaptativa y tela ANC Personalized.',             499.99, 'audio', '🎖️', NULL,           8, 4.80, 234),
('Focal Bathys',              'Auriculares audiófilo inalámbrico con cancelación activa y DAC/amp interno.',     799.99, 'audio', '🏅', NULL,           6, 4.90, 189),

-- ============================================================
-- OFICINA TECH (50)
-- ============================================================
('LG UltraFine 5K 27"',        'Monitor 5K con calibración automática de color y cubierta de vidrio nano.',     1299.99, 'oficina', '🖥️', NULL,          6, 4.80, 456),
('Dell UltraSharp 32" 4K',     'Monitor 4K con calibración IA, panel IPS Black y conector Thunderbolt 4.',      799.99, 'oficina', '💻', 'bestseller', 10, 4.80, 789),
('Samsung Smart Monitor M8',   'Monitor inteligente 4K con TV streaming y asistente voz Samsung integrado.',    699.99, 'oficina', '📺', NULL,          12, 4.70, 567),
('LG DualUp 28" SDQHD',        'Monitor cuadrado extendido 16:18 con USB-C 90W para máxima productividad.',    699.99, 'oficina', '🔲', 'nuevo',       8, 4.60, 345),
('BenQ PD3225U',               'Monitor 4K HDR de diseño con calibración Delta E≤2 y tecnología Aqcolor.',     699.99, 'oficina', '🎨', NULL,           8, 4.80, 234),
('Logitech MX Master 3S',      'Ratón ergonómico con desplazamiento MagSpeed y botón de acción por IA.',        99.99, 'oficina', '🖱️', 'bestseller', 30, 4.90, 4567),
('Logitech MX Keys S',         'Teclado inalámbrico inteligente con retroiluminación adaptativa y palm rest.',  109.99, 'oficina', '⌨️', 'bestseller', 25, 4.80, 3456),
('Apple Magic Keyboard Touch ID','Teclado inalámbrico con Touch ID y lápiz de escritura Palm Rejection.',       99.99, 'oficina', '🍎', NULL,          20, 4.80, 2345),
('Keychron Q5 Pro',            'Teclado mecánico 1800 con switches inalámbricos y bloqueador de ruido.',       219.99, 'oficina', '⌨️', NULL,          15, 4.80, 1234),
('Das Keyboard 6 Professional','Teclado con hub USB 3.0, switches Cherry MX y media roller analógico.',        189.99, 'oficina', '⌨️', NULL,          10, 4.70, 567),
('Logitech Lift Vertical',     'Ratón vertical ergonómico que reduce la tensión del antebrazo hasta un 25%.',   69.99, 'oficina', '🖱️', NULL,          25, 4.60, 2134),
('Anker Vertical Wireless Mouse','Ratón vertical con Bluetooth dual, ergonomía avanzada y silencioso.',         35.99, 'oficina', '🔵', NULL,          30, 4.50, 1567),
('Logitech MX Anywhere 3S',    'Ratón compacto de alta precisión con sensor 8000 DPI y scroll MagSpeed.',      79.99, 'oficina', '🖱️', NULL,          22, 4.70, 987),
('Apple Magic Trackpad',       'Trackpad con Force Touch y gestos de navegación multitáctil avanzados.',        129.99, 'oficina', '🍏', NULL,          20, 4.70, 1234),
('Logitech MX Ergo S',         'Trackball ergonómico con ángulo ajustable y flujo MX entre 2 equipos.',        99.99, 'oficina', '🔮', NULL,          15, 4.70, 789),
('Elgato Wave Link Desk Hub',  'Hub USB-C 10 en 1 con carga 100W y conmutador de audio integrado.',           199.99, 'oficina', '🔌', 'nuevo',       18, 4.70, 678),
('Anker 575 USB-C Hub 13en1',  'Hub con HDMI 4K, ethernet gigabit, lector SD y carga de 100W PD.',            79.99, 'oficina', '🔌', NULL,           25, 4.60, 2345),
('CalDigit TS4 Thunderbolt 4', 'Dock 98W con 18 puertos, 3 pantallas simultáneas y velocidad 40Gb/s.',        349.99, 'oficina', '🔗', 'bestseller',  12, 4.80, 1234),
('OWC Thunderbolt Go Dock',    'Dock Thunderbolt 4 portátil con HDMI 8K y carga de 96W en diseño delgado.',   299.99, 'oficina', '⚡', NULL,           10, 4.70, 456),
('Elgato Thunderbolt 4 Hub',   'Hub premium con 4 puertos Thunderbolt 4 de 40 Gb/s y carga 98W.',             149.99, 'oficina', '🌩️', NULL,          15, 4.60, 567),
('Logitech Brio 4K Webcam',    'Webcam 4K con corrección automática de luz y eliminación de ruido por IA.',   199.99, 'oficina', '📷', 'bestseller', 20, 4.80, 2345),
('Elgato Facecam Pro',         'Webcam 4K60 con sensor Sony y corrección de enfoque automático por IA.',      299.99, 'oficina', '📸', NULL,          12, 4.70, 1234),
('Razer Kiyo Pro Ultra',       'Webcam con sensor grande 1/1.2" y adaptación de exposición inteligente.',     299.99, 'oficina', '🎮', NULL,          10, 4.60, 678),
('Obsbot Tiny 2 Lite',        'Webcam 4K con seguimiento automático de persona y gesto de mano.',             199.99, 'oficina', '🤖', 'nuevo',       15, 4.70, 567),
('AnkerWork B600 Video Bar',   'Barra all-in-one con cámara 2K, altavoz y micrófono IA para video llamadas.', 249.99, 'oficina', '📡', NULL,          14, 4.60, 456),
('Flexispot E7 Pro',           'Escritorio elevable eléctrico con memoria de alturas y anti-colisión.',        699.99, 'oficina', '📐', 'bestseller', 10, 4.80, 1567),
('Uplift V2 Commercial',       'Escritorio de pie comercial con app de seguimiento de postura y tiempo.',      899.99, 'oficina', '🪑', NULL,           8, 4.80, 789),
('Autonomous SmartDesk Pro',   'Escritorio eléctrico con configuración por app y 4 perfiles de altura.',       499.99, 'oficina', '💡', NULL,          12, 4.70, 1234),
('Ergotron LX Monitor Arm',    'Brazo de monitor con rango de movimiento total y cable management integrado.',  179.99, 'oficina', '💪', 'bestseller', 20, 4.80, 3456),
('NB North Bayou Full Motion', 'Soporte de monitor con movimiento total y resorte de gas ajustable.',          59.99, 'oficina', '🔧', NULL,           25, 4.60, 2134),
('Humanscale M8.1 Monitor Arm','Brazo de monitor premium con sujeción constante y peso equilibrado.',         349.99, 'oficina', '⚖️', NULL,            8, 4.80, 345),
('Secretlab Titan Evo 2022',   'Silla gaming/oficina ergonómica con soporte lumbar magnético ajustable.',      449.99, 'oficina', '🪑', 'bestseller', 10, 4.80, 4567),
('Herman Miller Aeron',        'Silla ergonómica con soporte PostureFit SL y ajuste automático de reclinación.',1445.00,'oficina','🏆', NULL,           5, 4.90, 2345),
('Steelcase Leap V2',          'Silla de oficina con ajuste a la postura y mecanismo LiveBack.',               1299.99, 'oficina', '⚙️', NULL,           4, 4.90, 1234),
('Elgato Stream Deck MK.2',    'Controlador con 15 teclas LCD y automatización de flujos de trabajo por IA.', 149.99, 'oficina', '🎛️', 'bestseller', 20, 4.80, 3456),
('Elgato Stream Deck XL',      'Panel de control con 32 teclas LCD y perfiles ilimitados por IA.',            249.99, 'oficina', '🎮', NULL,          12, 4.70, 1567),
('Logitech Litra Glow',        'Lámpara de streaming con luz suave TrueSoft y control de temperatura de color.',79.99, 'oficina', '💡', 'nuevo',       22, 4.70, 1234),
('Elgato Key Light Air',       'Panel de luz LED con calibración de color y brillo por app y voz.',           129.99, 'oficina', '🌟', 'bestseller',  20, 4.80, 2345),
('BenQ ScreenBar Halo',        'Lámpara de monitor con luz trasera ambiental y sensor de luz automático.',    179.99, 'oficina', '🌈', NULL,          15, 4.80, 1567),
('Neat Board 50',              'Pizarra colaborativa 50" con IA de seguimiento de sala y Zoom certificado.',  2499.99, 'oficina', '📋', NULL,            3, 4.70, 89),
('Jabra PanaCast 50',          'Cámara de sala 180° con IA de encuadre dinámico y reconocimiento de personas.',1299.99,'oficina','📹', NULL,            5, 4.80, 234),
('Logitech Rally Bar Mini',    'Sistema de videoconferencia todo-en-uno con IA RightSight 2 autoencuadre.',    999.99, 'oficina', '📡', NULL,            6, 4.70, 156),
('Microsoft Surface Hub 3',    'Pizarra colaborativa 85" con IA de transcripción y equipos integrado.',      11999.99,'oficina','📊', NULL,             1, 4.80, 45),
('Rocketbook Fusion',          'Cuaderno reutilizable con plantillas, OCR y sincronización IA a la nube.',     34.99, 'oficina', '♻️', 'bestseller',  40, 4.60, 5678),
('Moleskine Smart Writing Set','Pluma y cuaderno digitalizador con IA de conversión de escritura a texto.',   229.99, 'oficina', '✒️', NULL,           15, 4.60, 456),
('Wacom One 13 Touch',         'Tablet gráfica con pantalla táctil y soporte de lápiz sin batería.',          399.99, 'oficina', '✏️', NULL,           12, 4.60, 567),
('ASUS ZenScreen MB16QHD',     'Monitor portátil 16" QHD con USB-C, trípode y protector incluido.',           299.99, 'oficina', '🖥️', NULL,           15, 4.60, 345),
('Lenovo ThinkVision M14t',    'Monitor portátil 14" IPS táctil con USB-C y soporte de lápiz activo.',       299.99, 'oficina', '📱', NULL,           12, 4.50, 234),
('Luxafor Flag',               'Indicador de disponibilidad LED con app de gestión de foco y modo Pomodoro.',  35.00, 'oficina', '🚦', NULL,           30, 4.30, 567),
('Poly Sync 40',               'Altavoz de conferencia con cancelación de ruido NoiseBlockAI y USB-C.',       249.99, 'oficina', '📞', 'nuevo',        15, 4.70, 456),
('Epos Adapt 661',             'Auriculares de oficina con IA de supresión de ruido y dongle USB.',           329.99, 'oficina', '🎧', NULL,            12, 4.60, 345),

-- ============================================================
-- JUGUETES & BEBÉS (50)
-- ============================================================
('Lego Mindstorms Robot Inventor','Set de robótica 949 piezas con app de programación visual por IA.',        359.99, 'juguetes', '🤖', 'bestseller', 20, 4.80, 2345),
('Sphero BOLT',               'Robot educativo programable en Swift, Scratch y JavaScript con sensores.',     149.99, 'juguetes', '⚡', 'bestseller', 18, 4.70, 1567),
('Makeblock mBot 2',          'Robot de codificación con sensores de visión por IA y 40+ experimentos.',     199.99, 'juguetes', '🤖', NULL,          15, 4.70, 987),
('Anki Cozmo Special Edition','Robot con IA de reconocimiento facial y personalidad que evoluciona sola.',    179.99, 'juguetes', '😄', 'bestseller', 10, 4.80, 3456),
('Wonder Workshop Dash Robot','Robot educativo que enseña programación a niños desde los 6 años.',           149.99, 'juguetes', '🌈', NULL,          18, 4.60, 1234),
('Coding Mouse Osmo',         'Ratón táctil con juegos de pensamiento computacional para niños 5-10.',        79.99, 'juguetes', '🐭', NULL,          22, 4.50, 789),
('Osmo Genius Starter Kit',   'Kit de educación STEM con juegos de tangram, números y letras con IA.',        99.99, 'juguetes', '🧩', 'bestseller', 20, 4.70, 2134),
('Merge Cube EDU',            'Cubo de realidad aumentada para explorar ciencia y matemáticas en 3D.',        19.99, 'juguetes', '🎲', NULL,          30, 4.50, 1567),
('Fisher-Price Linkimals',    'Juguete interactivo con animales que aprenden y se sincronizan entre sí.',      34.99, 'juguetes', '🦒', NULL,          28, 4.60, 987),
('LeapFrog Epic Academy',     'Tablet de aprendizaje 7" con más de 800 juegos educativos y control parental.', 79.99, 'juguetes', '📚', NULL,          20, 4.50, 1234),
('Amazon Fire HD 8 Kids',     'Tablet infantil 8" con funda resistente, control parental y 2 años garantía.', 139.99, 'juguetes', '📱', 'bestseller', 25, 4.60, 3456),
('DJI Tello Boost Combo',     'Drone educativo programable en Scratch con cámara HD y 13 minutos de vuelo.', 129.99, 'juguetes', '🚁', 'nuevo',       20, 4.60, 1234),
('Holy Stone HS170 Predator',  'Drone para principiantes con modo headless y protección 360 para niños.',      39.99, 'juguetes', '🚁', NULL,          30, 4.40, 2345),
('Parrot Mambo FPV',          'Mini drone con accesorios intercambiables y gafas FPV incluidas.',             149.99, 'juguetes', '✈️', NULL,          15, 4.50, 678),
('Lego Technic Ferrari Daytona','Set técnico 3778 piezas con motor real con indicadores y funcionamiento IA.',449.99, 'juguetes', '🏎️', 'bestseller', 12, 4.90, 1234),
('Lego Architecture NYC',     'Set de arquitectura 598 piezas del skyline de Nueva York.',                    119.99, 'juguetes', '🗽', NULL,           15, 4.80, 987),
('Lego Icons Botanical',      'Set botánico 830 piezas con flores y plantas reales de colección.',            99.99, 'juguetes', '🌸', NULL,           18, 4.80, 1567),
('Hot Wheels id Track Builder','Pista inteligente con autos NFC conectados a app de puntuación en tiempo real.',79.99,'juguetes','🚗','nuevo',        20, 4.50, 789),
('LEGO Education SPIKE Prime', 'Kit de robótica educativa con sensores, motores y plataforma de programación.',329.99,'juguetes','🔬','bestseller',  15, 4.80, 678),
('Gravitrax Pro Starter Set',  'Set de pistas de canicas con física y curvas eléctricas programables.',       149.99, 'juguetes', '🌀', NULL,          18, 4.70, 567),
('Moxie Robot for Kids',       'Robot amigo con IA conversacional que apoya el desarrollo socioemocional.',   799.99, 'juguetes', '🤗', 'nuevo',       8, 4.60, 234),
('Roybi Robot AI Tutor',       'Robot de aprendizaje con lecciones de idiomas e historias por IA adaptativa.',299.99,'juguetes','📖', NULL,           12, 4.50, 345),
('Lovot Companion Robot',      'Robot de compañía con emociones simuladas y reconocimiento facial por IA.',  2499.99,'juguetes','💕', NULL,            3, 4.70, 89),
('Clementoni Mio Coding Robot', 'Robot educativo para niños 5+ con tarjetas de programación sin pantalla.',   59.99, 'juguetes', '🐢', NULL,          25, 4.50, 789),
('Cubetto Primo Toys',         'Robot de madera Montessori para niños 3+ sin pantallas, puro tangible.',     224.99, 'juguetes', '🟦', NULL,          12, 4.60, 345),
('Eufy SpaceView Baby Monitor','Monitor de bebé con cámara motorizada, visión nocturna y alertas por IA.',   159.99, 'juguetes', '👶', 'bestseller', 20, 4.70, 2345),
('Nanit Pro Baby Monitor',     'Monitor con análisis de sueño por IA, temperatura ambiental y respiración.',  299.99, 'juguetes', '🌙', 'bestseller', 15, 4.70, 1567),
('Owlet Dream Sock 3',         'Sensor calcetín para bebé con monitoreo de oxígeno y frecuencia cardíaca IA.',  299.99,'juguetes','🧦','nuevo',       18, 4.60, 1234),
('Elvie Pump Double',          'Extractor de leche eléctrico silencioso con app de monitoreo inteligente.',   499.99, 'juguetes', '🍼', NULL,          12, 4.50, 678),
('Willow Go Breast Pump',      'Extractor portátil sin cable con app de seguimiento de sesiones y volumen.',  329.99, 'juguetes', '💙', NULL,          10, 4.40, 456),
('4moms mamaRoo 5',            'Mecedora que imita los movimientos naturales de los padres con app control.',  279.99, 'juguetes', '🍼', 'bestseller', 15, 4.60, 1234),
('SNOO Smart Sleeper',         'Cuna inteligente que detecta el llanto del bebé y responde con movimiento.',  1695.00,'juguetes','🛏️', NULL,            5, 4.70, 567),
('Hatch Rest+ 2nd Gen',        'Luz nocturna, máquina de ruido blanco y reloj con app de rutinas para bebé.', 89.99,'juguetes','🌟', 'bestseller',  25, 4.80, 3456),
('Lovevery Play Gym',          'Gimnasio de actividades con 40+ juguetes Montessori por etapa de desarrollo.', 149.99,'juguetes','🎈', NULL,          18, 4.80, 2134),
('Fisher-Price Think & Learn Smart Cycle','Bicicleta estática infantil con lecciones interactivas en pantalla.',79.99,'juguetes','🚲','nuevo',       15, 4.50, 789),
('VTech KidiZoom Studio',      'Estudio de foto y video infantil con efectos especiales y IA de filtros.',    69.99, 'juguetes', '📷', NULL,          20, 4.50, 1234),
('Learning Resources Botley 2','Robot de codificación sin pantalla con 77 piezas y 120+ actividades.',        79.99, 'juguetes', '🤖', NULL,          18, 4.60, 678),
('Toniebox Audio System',      'Sistema de cuentos infantil con figuras NFC y 90 horas de contenido.',       109.99, 'juguetes', '🎵', 'bestseller', 20, 4.80, 2345),
('Yoto Player Mini',           'Reproductor de audio infantil con cartas de actividad y sin pantalla.',        69.99, 'juguetes', '🎧', NULL,          22, 4.70, 1234),
('Pictionary Air',             'Juego de dibujo en el aire con bolígrafo invisible y app de detección IA.',   29.99, 'juguetes', '✏️', 'bestseller', 30, 4.50, 2134),
('Just Dance 2025 Controller', 'Controlador de baile inalámbrico con detección de movimiento y puntuación.',  49.99, 'juguetes', '💃', 'nuevo',       25, 4.40, 567),
('ThinkFun Gravity Maze',      'Juego de laberintos con canicas y retos de pensamiento lógico avanzado.',     34.99, 'juguetes', '🧠', NULL,          28, 4.70, 1567),
('Magformers 62-Piece',        'Bloques magnéticos de construcción 3D para aprendizaje STEM creativo.',       49.99, 'juguetes', '🔴', NULL,          25, 4.70, 987),
('Qobo Coding Robot Snail',    'Caracol robot de aprendizaje con laberintos y programación por tarjetas.',    89.99, 'juguetes', '🐌', NULL,          15, 4.50, 345),
('Snap Circuits Arcade',       'Kit de electrónica con proyectos de juego, sonido y luz para aprender.',      49.99, 'juguetes', '🔌', NULL,          20, 4.60, 789),
('National Geographic Geodes Kit','Kit de excavación de geodas con lupa y guía de minerales interactiva.',    24.99, 'juguetes', '💎', NULL,           30, 4.60, 1234),
('Educational Insights GeoSafari Jr.','Tableta educativa de exploración con sonidos de animales y naturaleza.',29.99,'juguetes','🦁','bestseller',  25, 4.50, 987),
('Smart Games IQ Circuit',     'Juego de lógica portátil con 120 desafíos de circuitos magnéticos.',         16.99, 'juguetes', '🔋', NULL,           30, 4.70, 1567),
('Ravensburger Gravity Buzz',  'Juego de equilibrio y gravedad para familia con desafíos progresivos.',       29.99, 'juguetes', '⚖️', NULL,           25, 4.60, 789),
('LEGO Super Mario Starter',   'Set interactivo con Mario electrónico, monedas de vida y señales de nivel.',  59.99, 'juguetes', '🍄', 'bestseller', 30, 4.80, 3456),

-- ============================================================
-- DEPORTES & OUTDOOR (50)
-- ============================================================
('Garmin Forerunner 965',      'Reloj GPS de running con IA de predicción de rendimiento y coach digital.',   599.99, 'deportes', '🏃', 'bestseller', 15, 4.80, 2345),
('Garmin Fenix 7X Solar',      'Reloj multideporte solar con mapas topográficos y análisis de energía IA.',  899.99, 'deportes', '☀️', 'bestseller', 12, 4.90, 3456),
('Polar Grit X2 Pro',          'Reloj outdoor con análisis de terreno, altímetro barométrico y ruta IA.',    499.99, 'deportes', '🏔️', NULL,          10, 4.80, 987),
('Coros Apex 2 Pro',           'Reloj GPS alpino con batería de 75h y asistente de trail running por IA.',   499.99, 'deportes', '🗻', NULL,          12, 4.70, 678),
('Suunto Vertical',            'Reloj outdoor con planificación de rutas satelital y mapas sin conexión.',   699.99, 'deportes', '🧭', NULL,           8, 4.70, 456),
('Garmin Tactix 7 Pro',        'Reloj táctico con modo stealth, mapas de noche y análisis de carga física.', 999.99, 'deportes', '🎯', NULL,           6, 4.80, 345),
('Wahoo ELEMNT Roam V2',       'Ciclocomputador con mapas y navegación turn-by-turn IA sin suscripción.',    379.99, 'deportes', '🚴', 'bestseller', 15, 4.80, 1234),
('Garmin Edge 840 Solar',      'Ciclocomputador solar con IA de subidas, ClimbPro y potencia virtual.',      499.99, 'deportes', '🔆', NULL,          12, 4.80, 987),
('Hammerhead Karoo 3',         'Ciclocomputador con pantalla táctil, guía de potencia IA y mapas offline.',  499.99, 'deportes', '🏁', 'nuevo',       10, 4.70, 567),
('Bryton Rider 750',           'Ciclocomputador GPS con analítica avanzada e integración con apps de entreno.',179.99,'deportes','🚴', NULL,           15, 4.60, 456),
('Polar Vantage M3',           'Reloj multideporte con test de fitness VO2max y planes de entreno por IA.',  299.99, 'deportes', '💚', NULL,           18, 4.70, 1234),
('Whoop 4.0 Strap',            'Banda de fitness continua con análisis de recuperación y strain por IA.',    239.99, 'deportes', '🏋️', 'bestseller', 25, 4.70, 3456),
('Fitbit Charge 6',            'Tracker con ECG, Google Maps y entrenamiento personalizado por IA Fitbit.',  159.99, 'deportes', '💪', NULL,           25, 4.60, 2345),
('Garmin Vivosmart 5',         'Pulsera fitness discreta con pulsioxímetro, estrés y actividades guiadas.',  149.99, 'deportes', '🎗️', NULL,           20, 4.50, 1234),
('Amazfit Balance',            'Smartwatch con IA de equilibrio bienestar físico-mental y coaching diario.', 199.99, 'deportes', '⚖️', NULL,           22, 4.60, 987),
('Zwift Hub One',              'Rodillo inteligente directo con cambio virtual controlado desde la app.',    499.99, 'deportes', '🔄', 'nuevo',        10, 4.80, 678),
('Elite Direto XR-T',          'Rodillo de bicicleta con potenciómetro integrado y simulación de 24% pendiente.',799.99,'deportes','🏔️',NULL,         8, 4.80, 456),
('Stages SC3 Smart Bike',      'Bicicleta estática de estudio con app Bluetooth y control de resistencia.',   1199.99,'deportes','🚵','bestseller',   6, 4.80, 345),
('Peloton Bike+',              'Bicicleta smart con instructor IA, inclinación automática y clases en vivo.', 2495.00,'deportes','🔥','bestseller',   5, 4.90, 2345),
('NordicTrack iFit Row',       'Remo con pantalla 22" y entrenador personalizado IA en agua y seco.',       1999.00, 'deportes', '🚣', NULL,            4, 4.70, 234),
('Hydrow Wave Rower',          'Máquina de remo con pantalla HD y clases en directo en agua real.',         1495.00, 'deportes', '💧', NULL,            4, 4.70, 189),
('Garmin Descent Mk3i',        'Reloj de buceo con tabla de descompresión IA y mapa subacuático.',           999.99, 'deportes', '🤿', NULL,            5, 4.80, 234),
('Stryd Running Power Meter',  'Sensor de potencia de carrera con detección de forma y IA de predicción.',   219.99, 'deportes', '⚡', 'nuevo',        15, 4.70, 567),
('RunScribe Gait Lab',         'Sensor de biomecánica de carrera con análisis de forma y riesgo lesión IA.', 179.99, 'deportes', '🦶', NULL,           12, 4.60, 345),
('Vald ForceDecks Lite',       'Plataforma de salto con análisis de asimetría y potencia para entrenadores.',1499.99,'deportes','📊',NULL,             3, 4.70, 45),
('Rapsodo Mobile Launch Monitor','Monitor de golf con cámara IA, spin y análisis de trayectoria de bola.',  499.99, 'deportes', '⛳', NULL,            8, 4.60, 234),
('Shot Scope V5',              'Reloj de golf con GPS de 40.000 campos y análisis de swing por IA.',        279.99, 'deportes', '🏌️', NULL,            10, 4.60, 345),
('GreenOn Robi II',            'Caddie GPS de golf con IA de lectura de green y recomendación de palo.',    549.99, 'deportes', '🏌️', 'nuevo',         6, 4.50, 156),
('Adidas Smart Ball Micoach',  'Balón de fútbol con sensor de potencia, efecto y velocidad de tiro.',       219.99, 'deportes', '⚽', NULL,            15, 4.40, 456),
('Wilson Shift Tennis Racket', 'Raqueta con sensor integrado que analiza golpe, spin y puntos de impacto.',  249.99, 'deportes', '🎾', NULL,            12, 4.50, 345),
('Zepp Tennis 2 Sensor',       'Sensor de tenis que analiza golpes, velocidad y consistencia por IA.',       99.99, 'deportes', '🎾', NULL,            18, 4.40, 456),
('Arccos Golf Caddie Smart Set','14 sensores de palos con IA que aprende tu juego y recomienda estrategia.', 179.99,'deportes','⛳','bestseller',     12, 4.70, 789),
('GoPro HERO13 Black',         'Cámara de acción 5.3K con HyperSmooth 6.0 y estabilización por IA.',       399.99, 'deportes', '🎬', 'bestseller',   20, 4.80, 4567),
('DJI Action 4',               'Cámara de acción 4K con sensor grande y estabilización RockSteady Ultra.',  399.99, 'deportes', '🏄', NULL,            18, 4.70, 2345),
('Insta360 Ace Pro 2',         'Cámara de acción 8K con IA de estabilización y edición de clips automática.',449.99,'deportes','🎥','nuevo',          15, 4.70, 987),
('Garmin XERO A1i Pro Bow Sight','Mira de arco digital con compensación de pendiente y ángulo por IA.',    999.99, 'deportes', '🏹', NULL,             4, 4.80, 89),
('Theragun Pro Plus',          'Masajeador percusivo con guías de recuperación IA y calor integrado.',      599.99, 'deportes', '💆', 'bestseller',   18, 4.80, 2345),
('Hypervolt 2 Pro',            'Pistola de masaje con app de rutinas y adaptación de velocidad automática.', 299.99, 'deportes', '💪', NULL,            20, 4.70, 1567),
('Compex SP 8.0',              'Electroestimulador muscular con IA de programas de recuperación y rendimiento.',699.99,'deportes','⚡','nuevo',         8, 4.70, 456),
('Garmin HRM-Pro Plus',        'Sensor cardíaco de pecho con memoria de actividades y dinámica de running.', 129.99, 'deportes', '❤️', NULL,           20, 4.70, 1234),
('Wahoo Tickr X',              'Monitor cardíaco con acelerómetro y análisis de mecánica de carrera.',       99.99, 'deportes', '💗', NULL,            22, 4.60, 987),
('Oakley Radar EV Path',       'Gafas deportivas con lente Prizm que adapta el contraste al entorno.',      249.99, 'deportes', '😎', NULL,            15, 4.70, 789),
('Bollé Chronoshield',         'Gafas de ciclismo con ventilación Flow-Tech y lente fotocromática adaptativa.',199.99,'deportes','🕶️',NULL,            12, 4.60, 456),
('NightRider Lumina 1500',     'Luz frontal para bici de 1500 lúmenes con sensor de luz automático.',       119.99, 'deportes', '💡', NULL,            18, 4.70, 567),
('Garmin Varia RCT715',        'Radar trasero de ciclismo con cámara y alerta de vehículos que se acercan.', 249.99, 'deportes', '🚨', 'nuevo',        12, 4.70, 456),
('Wahoo Kickr Headwind Fan',   'Ventilador inteligente que regula velocidad según ritmo cardíaco o potencia.', 169.99, 'deportes', '🌬️', NULL,          15, 4.60, 789),
('Supersapiens Glucose Monitor','Monitor de glucosa deportivo con app de nutrición y energía en tiempo real.',249.99,'deportes','📊','nuevo',           10, 4.50, 234),
('FORM Swim Goggles',          'Gafas de natación con display HUD que muestra ritmo, vuelta y distancia.',   199.99, 'deportes', '🏊', 'bestseller',   15, 4.70, 1234),
('Swimmo Aqua Smartwatch',     'Reloj de natación con reconocimiento automático de estilo y conteo de largos.',199.99,'deportes','🏊',NULL,            12, 4.50, 456),
('iFit Race Ski Trainer Pro',  'Simulador de esquí nórdico con pantalla táctil y clases en tiempo real.',  2199.00, 'deportes', '⛷️', NULL,             2, 4.70, 45),

-- ============================================================
-- ELECTRÓNICA (50)
-- ============================================================
('Samsung 65" QLED 4K Q80D',   'Smart TV 4K con procesador NQ4 IA, Motion Xcelerator y Quantum HDR.',      1099.99, 'electronica', '📺', 'bestseller', 10, 4.80, 1234),
('LG 65" OLED evo C4',         'Smart TV OLED 4K con procesador α9 Gen7 IA y Dolby Vision IQ.',           1799.99, 'electronica', '🖥️', 'bestseller',  6, 4.90, 2345),
('Sony 65" Bravia 9',          'Smart TV Mini LED 4K con procesador XR y calibración IA de imagen perfecta.',2499.99,'electronica','🎬',NULL,           4, 4.90, 567),
('Hisense 75" U7N',            'Smart TV ULED 4K 144Hz con IA de mejora de imagen y Dolby Atmos integrado.', 799.99,'electronica','📡',NULL,          10, 4.70, 789),
('TCL 55" QM8 Mini LED',       'Smart TV 4K 240Hz con retroiluminación local y Google TV con Gemini IA.',    599.99, 'electronica', '💡', 'descuento',  12, 4.70, 1234),
('Nvidia Shield TV Pro',       'Reproductor streaming 4K con IA de upscaling y servidor Plex integrado.',   199.99, 'electronica', '🎮', 'bestseller', 20, 4.90, 4567),
('Apple TV 4K 3rd Gen',        'Reproductor con chip A15, Dolby Vision y calibración de color IA en sala.',  129.99, 'electronica', '🍎', 'bestseller', 25, 4.80, 5678),
('Amazon Fire TV Cube Gen3',   'Reproductor streaming manos libres con Alexa y upscaling 4K por IA.',        139.99, 'electronica', '🔥', NULL,          22, 4.70, 2345),
('Google Chromecast 4K',       'Streamer 4K con Google TV y recomendaciones personalizadas por Gemini IA.',   49.99, 'electronica', '🌐', NULL,          30, 4.60, 3456),
('Roku Streaming Stick 4K+',   'Stick compacto con control de voz privado, Dolby Vision y WiFi 6.',          59.99, 'electronica', '📺', NULL,           28, 4.60, 2134),
('PlayStation 5 Pro',          'Consola con trazado de rayos mejorado, upscaling PSSR por IA y 2TB SSD.',   699.99, 'electronica', '🎮', 'bestseller', 15, 4.90, 6789),
('Xbox Series X',              'Consola 4K/120fps con Quick Resume, Game Pass y FPS Boost por IA.',         499.99, 'electronica', '🎯', 'bestseller', 18, 4.80, 5678),
('Nintendo Switch 2',          'Consola híbrida nueva generación con pantalla HDR y modo colaborativo.',    449.99, 'electronica', '🕹️', 'nuevo',       20, 4.80, 3456),
('Steam Deck OLED 1TB',        'PC gaming portátil con pantalla OLED y acceso a toda la librería de Steam.', 649.99, 'electronica', '🎮', 'bestseller', 12, 4.80, 2345),
('Asus ROG Ally X',            'PC gaming portátil con Ryzen Z1 Extreme y pantalla FHD de 120Hz.',          799.99, 'electronica', '🏆', NULL,          10, 4.70, 1234),
('Epson EF-21 Mini Laser',     'Proyector láser compacto Full HD con Android TV y 1000 lúmenes.',           499.99, 'electronica', '🎥', 'nuevo',       12, 4.70, 567),
('Xgimi Horizon Ultra',        'Proyector 4K UHD con Dolby Vision, ISA 3.0 de ajuste automático de imagen.',1499.99,'electronica','📽️','bestseller',   8, 4.80, 789),
('Formovie Theater',           'Proyector láser 4K UST con 2800 lúmenes y sistema de sonido Dolby.',       2999.99, 'electronica', '🎬', NULL,           3, 4.80, 234),
('BenQ GP20',                  'Proyector portátil Android TV con autofoco, autocorrección y batería.',      499.99, 'electronica', '💡', NULL,          10, 4.60, 345),
('Dangbei Mars Pro 2',         'Proyector láser 4K con tiro corto, Dolby Vision y calibración IA de imagen.',1999.99,'electronica','🌟',NULL,           4, 4.70, 189),
('Arlo Pro 5S 2K',             'Cámara de seguridad 2K con IA de detección de paquetes y personas.',        199.99, 'electronica', '📷', 'bestseller', 18, 4.70, 2345),
('Ring Video Doorbell Pro 2',  'Timbre con cámara 3D, detección de zona y visión nocturna a color.',        249.99, 'electronica', '🔔', 'bestseller', 20, 4.70, 3456),
('Eufy Security S300 4K',      'Cámara 4K con almacenamiento local, IA de reconocimiento facial sin nube.', 179.99, 'electronica', '🔒', NULL,          15, 4.80, 1567),
('Google Nest Cam Indoor',     'Cámara inteligente con detección de personas y alertas por IA sin suscripción.',99.99,'electronica','🏠',NULL,          20, 4.60, 2134),
('Reolink Argus 4 Pro',        'Cámara solar 4K con detección de IA de coches y personas, sin cables.',     149.99, 'electronica', '☀️', NULL,          18, 4.60, 1234),
('Amazon Echo Show 15',        'Pantalla inteligente 15" con Alexa, fotos familiares y widgets IA.',        249.99, 'electronica', '🖥️', NULL,          15, 4.60, 987),
('Google Nest Hub Max',        'Pantalla inteligente 10" con sensor de presencia y reconocimiento facial.',  229.99, 'electronica', '🌐', NULL,          18, 4.60, 1234),
('TP-Link Deco BE85',          'Mesh WiFi 7 triband con 21 Gbps y IA de optimización de tráfico de red.',   599.99, 'electronica', '📡', 'nuevo',       12, 4.80, 678),
('Eero Max 7',                 'Router mesh WiFi 7 con 4.3 Gbps y IA de seguridad de red doméstica.',      599.99, 'electronica', '🔒', NULL,          10, 4.70, 567),
('Netgear Orbi 960',           'Sistema mesh WiFi 6E de 4 bandas con cobertura de 900 m² y IA de banda.',  1499.99, 'electronica', '🌐', NULL,           5, 4.80, 234),
('Philips Hue Gradient Strip',  'Tira LED con degradado de colores y sincronización con contenido de TV.',   149.99, 'electronica', '🌈', NULL,          20, 4.70, 1567),
('Nanoleaf Lines Squared',     'Líneas de luz modulares hexagonales con reacción a música por IA.',          199.99, 'electronica', '🌟', 'bestseller', 15, 4.70, 2345),
('LIFX Candle Color',          'Bombilla inteligente RGBW con zonas de color y control por voz.',           19.99, 'electronica', '💡', NULL,           30, 4.50, 1567),
('Govee H6008 RGB Lamps',      'Lámparas de mesa RGB con sincronización musical y control por app.',         49.99, 'electronica', '🎨', NULL,           25, 4.50, 2134),
('Meross Smart Plug 4-Pack',   'Enchufes inteligentes con medición de energía y automatización por IA.',     35.99, 'electronica', '🔌', 'bestseller', 30, 4.60, 3456),
('TP-Link Kasa Cam 2K Pan Tilt','Cámara de interior con paneo 360° y seguimiento de movimiento por IA.',     49.99, 'electronica', '📸', NULL,           25, 4.50, 2134),
('Ecobee Premium Thermostat',  'Termostato con sensor de ocupación IA, Siri/Alexa y ahorro de energía.',   249.99, 'electronica', '🌡️', 'bestseller', 18, 4.70, 2345),
('Aqara Hub M3',               'Centro de automatización del hogar con Zigbee, Thread y Matter integrado.',  99.99, 'electronica', '🏠', NULL,          20, 4.60, 789),
('Lutron Caseta Wireless',     'Interruptor inteligente con Pico Remote y compatibilidad total con plataformas.',79.99,'electronica','💡',NULL,          22, 4.70, 1234),
('Level Bolt Smart Lock',      'Cerradura que se instala dentro de la cerradura existente, invisible.',       199.99, 'electronica', '🔐', NULL,          15, 4.60, 567),
('August Smart Lock Pro',      'Cerradura inteligente con acceso automático y registro de historial IA.',    199.99, 'electronica', '🗝️', NULL,          18, 4.60, 789),
('Irobot Roomba Combo j9+',    'Robot aspirador y fregasuelos con vaciado automático y mapeo IA.',          899.99, 'electronica', '🤖', 'bestseller', 10, 4.80, 1567),
('Dyson 360 Vis Nav',          'Robot aspirador con 360° de visión y torque sin escobilla para todo suelo.', 999.99, 'electronica', '🦾', NULL,           8, 4.80, 678),
('Roborock Qrevo Master',      'Robot 2en1 con estación de lavado de mopa caliente y vaciado automático.',  1199.99, 'electronica', '🧹', 'nuevo',        6, 4.80, 456),
('Xiaomi Robot Vacuum X20',    'Robot con sensor LIDAR, mopa vibratoria y mapeo 3D de la casa.',             599.99, 'electronica', '🔵', NULL,          12, 4.60, 789),
('Narwal Freo Z Ultra',        'Robot aspirador-fregasuelos con estación inteligente de limpieza automática.',999.99,'electronica','🌊',NULL,            6, 4.70, 345),
('Braava Jet m6',              'Robot fregasuelos con rutas de limpieza personalizadas por IA y alfombras.',  449.99, 'electronica', '🫧', NULL,          12, 4.60, 789),
('Dreame X40 Ultra',           'Robot 2en1 con extensión de cepillo lateral y navegación inteligente 3D.',  1099.99, 'electronica', '⚡', 'nuevo',        5, 4.80, 234),
('Tineco Floor One S7 Pro',    'Fregona inalámbrica inteligente con sensor de suciedad y auto lavado.',      449.99, 'electronica', '🧺', NULL,          12, 4.70, 567),
('SharkNinja AI Robot Pro',    'Robot aspirador con cámara frontal IA y detección de objetos en tiempo real.',499.99,'electronica','🦈','descuento',    10, 4.60, 456),

-- ============================================================
-- TELÉFONOS & ACCESORIOS (50)
-- ============================================================
('MagSafe Charger Apple 2m',   'Cargador magnético oficial 15W con cable de 2 metros para iPhone.',          49.99, 'telefonos', '🍎', 'bestseller', 40, 4.70, 3456),
('Anker MagGo 3in1 Stand',     'Cargador inalámbrico 3en1 con soporte MagSafe para iPhone, Watch y AirPods.', 79.99,'telefonos','⚡','bestseller',    30, 4.80, 4567),
('Belkin BoostCharge 15W',     'Cargador Qi2 de 15W con soporte plegable y cable USB-C incluido.',           59.99, 'telefonos', '🔋', NULL,           25, 4.70, 2134),
('Mophie Snap+ 3in1 Travel',   'Cargador de viaje magnético con soporte de escritorio y 15W MagSafe.',       99.99, 'telefonos', '✈️', NULL,           20, 4.70, 987),
('Anker 737 GaN Charger',      'Cargador de 120W GaN con 3 puertos para cargar laptop, tablet y móvil.',     55.99, 'telefonos', '⚡', 'bestseller', 30, 4.80, 5678),
('Samsung 65W Super Fast Adapter','Adaptador de carga rápida 65W con cable USB-C para Galaxy y Galaxy AI.', 49.99, 'telefonos', '🔵', 'bestseller', 25, 4.70, 2345),
('Apple 30W USB-C Adapter',    'Adaptador compacto 30W para carga rápida de iPhone 15 y MacBook.',           29.99, 'telefonos', '🍏', NULL,           30, 4.60, 1567),
('Ugreen Nexode 300W GaN',     'Cargador de escritorio 6 puertos con carga inteligente de distribución IA.', 129.99, 'telefonos', '🔌', NULL,          15, 4.70, 678),
('Baseus 67W Magnetic Power Bank','Batería magnética 10000mAh MagSafe con pantalla LED de capacidad.',       69.99, 'telefonos', '🧲', 'bestseller', 25, 4.70, 3456),
('Anker 633 Magnetic Battery', 'Batería MagSafe de 10000mAh con carga inalámbrica de 7.5W integrada.',       55.99, 'telefonos', '💚', NULL,           22, 4.60, 2134),
('Spigen ArcField Charging Pad','Base de carga MagSafe 15W con certificación MFi y carga rápida.',           35.99, 'telefonos', '🔵', NULL,           25, 4.60, 1234),
('Casetify Ultra Impact Case',  'Funda ultrarresistente ante caídas de 3.6 metros con bordes con rebote.',    59.99, 'telefonos', '🛡️', 'bestseller', 30, 4.80, 5678),
('Apple Clear Case MagSafe',   'Funda transparente oficial con anillo MagSafe para iPhone 16 Pro.',           49.99, 'telefonos', '🍎', NULL,           28, 4.70, 3456),
('Peak Design Everyday Case',   'Funda modular con sistema de montaje MagSafe y cuero vegetal premium.',      79.99, 'telefonos', '📷', NULL,           15, 4.80, 2134),
('Spigen Slim Armor CS',        'Funda con ranura para tarjetas, MagSafe y absorción de impactos militar.',  29.99, 'telefonos', '💳', 'bestseller',  35, 4.70, 4567),
('Dbrand Teardown Case',        'Funda transparente con diseño interior del dispositivo impreso a detalle.',  49.99, 'telefonos', '🔬', NULL,           20, 4.80, 1234),
('Zagg InvisibleShield Ultra',  'Protector de pantalla de vidrio con garantía de reemplazo de por vida.',    49.99, 'telefonos', '🔒', 'bestseller', 35, 4.70, 3456),
('Belkin TemperedGlass ProGrade','Cristal templado con aplicador de posicionamiento perfecto garantizado.',  14.99, 'telefonos', '💎', NULL,           40, 4.60, 5678),
('ESR ArmorPro Glass',          'Vidrio templado 9H con recubrimiento antihuella y borde a borde perfecto.',  9.99, 'telefonos', '🛡️', NULL,           40, 4.50, 7890),
('PopSockets MagSafe',          'Soporte magnético MagSafe con agarre ergonómico y diseños personalizables.', 19.99, 'telefonos', '🎨', 'bestseller', 50, 4.60, 8901),
('MagSafe Wallet Apple',        'Cartera magnética oficial con lector de Dónde está y capacidad 3 tarjetas.', 59.99, 'telefonos', '👛', NULL,           25, 4.50, 2345),
('Peak Design Wallet MagSafe',  'Cartera magnética de aluminio con mecanismo de apertura con un dedo.',       59.99, 'telefonos', '💼', NULL,           20, 4.70, 1234),
('Orbitkey Ring Key Organizer', 'Organizador de llaves minimalista con fijación silenciosa y cuero premium.',  49.99, 'telefonos', '🔑', NULL,           25, 4.70, 987),
('ESR HaloLock Kickstand',      'Funda con soporte MagSafe ajustable para posición horizontal y vertical.',  34.99, 'telefonos', '📱', NULL,           28, 4.60, 1567),
('Logitech Combo Touch iPad',   'Funda con teclado trackpad retroiluminado para iPad Air y compatible Smart Connector.',149.99,'telefonos','⌨️','bestseller',20,4.70,3456),
('Apple Smart Folio iPad Pro',  'Funda folio oficial para iPad Pro con frente inteligente y soporte.',        99.99, 'telefonos', '🍎', NULL,           22, 4.60, 2134),
('Moft Float Invisible Stand',  'Soporte invisible adhesivo para iPhone con ángulos múltiples y MagSafe.',    29.99, 'telefonos', '🌫️', NULL,           30, 4.60, 1234),
('Anker 543 USB-C to Lightning','Cable trenzado USB-C a Lightning de 1.8m certificado MFi de alta durabilidad.',12.99,'telefonos','🔵',NULL,          40, 4.60, 4567),
('Nomad 100W USB-C Cable',      'Cable USB-C Premium Kevlar de 3m, ultra resistente con 100W de carga.',     29.99, 'telefonos', '🔗', NULL,           30, 4.70, 2134),
('Syncwire USB-C Cable 3Pack',  'Pack 3 cables USB-C de 1m, 2m y 3m nylon trenzado con 60W de carga.',       14.99, 'telefonos', '🔌', 'bestseller', 40, 4.60, 5678),
('Moment iPhone Lens System',   'Sistema de lentes intercambiables para iPhone con óptica de calidad pro.',   99.99, 'telefonos', '📸', NULL,           15, 4.80, 789),
('Olloclip Starter Kit',        'Kit de lentes wide, fisheye y macro que se adhieren al teléfono en segundos.',49.99,'telefonos','🔭',NULL,            18, 4.60, 456),
('Joby GorillaPod Smartphone', 'Trípode flexible articulado para smartphone con cabezal de bola ajustable.',  49.99, 'telefonos', '🎥', NULL,           22, 4.70, 1234),
('Peak Design Travel Tripod',  'Trípode de viaje ultracompacto de carbono compatible con smartphones.',      579.99, 'telefonos', '📷', NULL,            8, 4.80, 567),
('Insta360 Flow Pro',           'Gimbal inteligente con seguimiento por IA, trípode integrado y linterna.',   149.99, 'telefonos', '🎬', 'bestseller', 18, 4.80, 2345),
('DJI OM 6',                   'Gimbal de 3 ejes con ActiveTrack 6.0 para seguimiento de sujeto por IA.',    159.99, 'telefonos', '🤖', NULL,           15, 4.70, 1567),
('Zhiyun Smooth 5S',            'Gimbal profesional con pantalla de control integrada y brazo extensor.',    199.99, 'telefonos', '🎥', NULL,           10, 4.70, 678),
('Nekteck USB-C Hub 6en1',      'Hub USB-C con HDMI 4K, 3 puertos USB-A, tarjeta SD y carga de 100W PD.',    35.99, 'telefonos', '🔌', NULL,           30, 4.60, 2345),
('HyperDrive Next 10in1',       'Hub USB-C compacto con HDMI 8K, Ethernet y DisplayPort para laptop.',       99.99, 'telefonos', '🔗', NULL,           20, 4.70, 1234),
('Satechi 165W 6en1 GaN',       'Cargador de escritorio 6 puertos con distribución inteligente de potencia.',  99.99,'telefonos','⚡','nuevo',          18, 4.70, 567),
('Twelve South MagSafe Shelf', 'Repisa de pared para iPhone con MagSafe y carga Qi2 de 15W integrada.',      59.99, 'telefonos', '📱', NULL,           20, 4.60, 345),
('Magtame Cable Organizer',     'Organizador de cables magnético con 3 en 1: Lightning, USB-C y micro USB.',   29.99, 'telefonos', '🧲', NULL,           30, 4.50, 1234),
('KeySmart CleanTray UV',       'Bandeja UV-C que desinfecta el teléfono en 90 segundos sin rayos directos.',  29.99, 'telefonos', '🔆', NULL,           25, 4.40, 789),
('PhoneSoap Go UV Sanitizer',   'Estuche portatil de desinfección UV-C para teléfono con carga incluida.',    79.99, 'telefonos', '🧼', NULL,           18, 4.40, 567),
('Pitaka MagEZ Case Pro',       'Funda de aramida ultrafina 0.95mm con MagSafe y acabado 3D premium.',        79.99, 'telefonos', '🛡️', NULL,           15, 4.80, 1234),
('Totallee Super Thin Case',    'Funda más delgada del mundo 0.85mm que preserva el diseño original.',        34.99, 'telefonos', '🌬️', NULL,           20, 4.50, 987),
('Mujjo Full Leather Wallet',   'Funda de cuero genuino con bolsillo de tarjeta y acabado premium.',          49.99, 'telefonos', '👜', NULL,           15, 4.70, 789),
('Ghostek Exec 6',              'Funda tipo cartera de cuero con protección militar y ranura magnética.',      39.99, 'telefonos', '💼', NULL,           18, 4.50, 456),
('Smartish Wallet Slayer Vol1', 'Funda con 3 bolsillos para tarjetas, grip de dedos y borde elevado.',        15.99, 'telefonos', '💳', 'bestseller', 35, 4.60, 3456),
('MOFT Snap Phone Stand',       'Soporte invisible adhesivo MagSafe de aluminio con 3 ángulos de uso.',       39.99, 'telefonos', '🔲', NULL,           25, 4.60, 1234);
